### ISSUE TITLE
UBL rules: Add check on normalize-space to all rules where a code is used

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#10]
In the EN16931-UBL-codes.sch the check to find valid codes is using the normalize-space function. However, when we for the VAT rules perform checks/calculations based on a VAT category, there is no normalize-space function. 

This results in that a file with
	`<cbc:ID> S</cbc:ID>`

Will not be handled as standard rate "S". Example in most of the VAT rules (BR-S-09 as one example). Similar issues for PaymentMeans in rule BR-61 and there might be more.

**Comment by SiwMeckelborg** [comment]
In the definitions of the patterns for the schematron rules, this is not corrected, example: <param name="VATS" value="cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory[cbc:ID = 'S']"/>

Please add normalize-space in these xPaths as well.

**Comment by oriol** [comment]
Can you please send the example?
