### ISSUE TITLE
Confusions around supplier’s VAT number - issue 2(2) - generalization [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#100]
TaxScheme/ID=”VAT” may be present in many places in an invoice document. As a matter of principle, all validations of TaxScheme/ID=”VAT” 
•	Either should be made against upper case “VAT”, or 
•	Otherwise the documentation need to be improved so that everyone is alerted about potential issues with upper and lower cases when using TaxScheme/ID. (In my view, this latter option is less attractive.)

**Comment by oriol** [comment]
added the upper-case function when checking the VAT for the TaxScheme identifier
