### ISSUE TITLE
Violation of VAT tax scheme rule triggers no error signal [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#101]
AccountingCustomerParty/Party is to have PartyTaxScheme with TaxScheme/ID=”VAT” or no PartyTaxScheme at all (i.e.. 0..1). Why is not an error signal fired in the case below?

	<cac:AccountingCustomerParty>
		<cac:Party>
			<cbc:EndpointID schemeID="0007">1234512345</cbc:EndpointID>
			<cac:PostalAddress>
				<cac:Country>
					<cbc:IdentificationCode>AF</cbc:IdentificationCode>
				</cac:Country>
			</cac:PostalAddress>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AF9988776655</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>WHAT</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyLegalEntity>
				<cbc:RegistrationName>TESTNAME</cbc:RegistrationName>
			</cac:PartyLegalEntity>
		</cac:Party>
	</cac:AccountingCustomerParty>

Request: Introduce validation rule with severity signal fatal

**Comment by oriol** [comment]
Added the check for the TaxScheme identifier in rule UBL-SR-18

**Comment by SiwMeckelborg** [comment]
I assume correct rule reference is UBL-SR-18, not 14. But UBL-SR-18, will only fire if there are more than one occurance of TaxScheme ='VAT', it will not fire if there is none. However, the Buyer VAT number is optional/conditional, and it's existence is checked in the VAT rules that requires this element. But I think that having a ubl-syntax rule, giving a warning if the AccountingCustomer/Party/Party/PartyTaxScheme exist without the TaxScheme='VAT' might be a way to solve this?

**Comment by oriol** [comment]
The rule says: [UBL-SR-18]-Buyer VAT identifier shall occur maximum once.

It does not say that shall be at least one.

**Comment by SiwMeckelborg** [comment]
The rule says maximum once, yes, but then that rule does not solve the issue reported from Sören, as he is asking why the example does not fire any rules, and in his example the TaxScheme = "WHAT" not VAT

**Comment by oriol** [comment]
Because the rule does not say that if there is no VAT Tax Scheme, it shall not have any other Tax Scheme.

BT-31 and BT-32 are mapped to the same element cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:Company, having BT-31 cac:TaxScheme/cbc:ID = "VAT" and BT-32 cac:TaxScheme/cbc:ID != "VAT". In the example from Soren, I assume WHAT is qualifying BT-32
