### ISSUE TITLE
Violation of cardinality rule triggers a strange warning signal [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#102]
AccountingCustomerParty/Party/PartyTaxScheme has cardinality 0..1
Why is not an error signal fired in the case below?

	<cac:AccountingCustomerParty>
		<cac:Party>
			<cbc:EndpointID schemeID="0007">1234512345</cbc:EndpointID>
			<cac:PostalAddress>
				<cac:Country>
					<cbc:IdentificationCode>AF</cbc:IdentificationCode>
				</cac:Country>
			</cac:PostalAddress>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AF9988776655</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>VAT1</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AF9988776655</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>VAT2</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyLegalEntity>
				<cbc:RegistrationName>TESTNAME</cbc:RegistrationName>
			</cac:PartyLegalEntity>
		</cac:Party>
	</cac:AccountingCustomerParty>

Currently the following error is generated:
“Warning  [UBL-SR-18]-Buyer VAT identifier shall occur maximum once”

Request: Introduce validation rule with severity signal fatal.

**Comment by oriol** [comment]
changed severity to fatal for rule UBL-SR-18
