### ISSUE TITLE
Violation of cardinality rule (Payee) triggers strange warning signals [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#103]
PayeeParty/PartyIdentification has cardinality 0..1
Why is not an error signal fired in the case below?

	<cac:PayeeParty>
		<cac:PartyIdentification>
			<cbc:ID schemeID="0007">2224446660</cbc:ID >
		</cac:PartyIdentification>
		<cac:PartyIdentification>
			<cbc:ID schemeID="0088">1122334455667</cbc:ID >
		</cac:PartyIdentification>
		<cac:PartyName>
			<cbc:Name>Finansiell Support u.p.a.</cbc:Name>
		</cac:PartyName>
		<cac:PartyLegalEntity>
			<cbc:CompanyID schemeID="0007">5566778899</cbc:CompanyID>
		</cac:PartyLegalEntity>
	</cac:PayeeParty>

The excerpt generates 2 warning signals, as follows:
warning	[UBL-SR-29]-Bank creditor reference shall occur maximum once
warning	[UBL-SR-20]-Payee identifier shall occur maximum once, if the Payee is different from the Seller

Requests:
1. Raise the severity code for UBL-SR-20 to “fatal”.
2. Clarify if UBL-SR-29 should be present all as no schemeID refers to SEPA.

**Comment by oriol** [comment]
Fixed UBL-SR-29 to allow maximum of 1 party identifier with a SEPA scheme ID.

Raised severity for rule UBL-SR-20 to fatal. Check of number of identifiers limited to the ones not SEPA.
