### ISSUE TITLE
The mappning of payment means type code [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#105]
BG-16 Payment instructions has cardinality 0..1 and BT-81 Payment means type code has cardinality 0..1. Through the syntax binding to UBL, BT-81 is mapped to PaymentMeansCode in PaymentMeans, where PaymentMeans has cardinality 0..n.

In line with the specification in EN, multiple occurrences of PaymentMeans may exist in case the transaction is to generate payment via credit transfer (BG-17). 

Request: A validation rule is needed to secure that at most one value for PaymentMeansCode may exist in a UBL invoice or credit note.

**Comment by oriol** [comment]
As PaymentMeansCode is mandatory inside the PaymentMeans: should there be more than one PaymentMeans, there will be more than one PaymentMeansCode.

In case there are more than one PaymentMeans, the PaymentMeansCode shall be equal to avoid misunderstandings.

**Comment by oriol** [comment]
Using XPath 2.0 would be: count(distinct-values(//cbc:PaymentMeansCode) ) = 1

Workaround using XPath 1.0... just compare the two initial PaymentMeansCode if they exist.

(count(cac:PaymentMeans) &gt; 1 and (cac:PaymentMeans[1]/cbc:PaymentMeansCode = cac:PaymentMeans[2]/cbc:PaymentMeansCode ))  or (count(cac:PaymentMeans) &lt; 1)
