### ISSUE TITLE
The mappning of payment means text [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#106]
BG-16 Payment instructions has cardinality 0..1 and BT-82 Payment means text has cardinality 0..1. Through the syntax binding to UBL, BT-82 is mapped to attribute PaymentMeansCode/@name in PaymentMeans, where PaymentMeans has cardinality 0..n.

In line with the specification in EN, multiple occurrences of PaymentMeans may exist in case the transaction is to generate payment via credit transfer (BG-17). 

Request: A validation rule is needed to secure that at most one value for PaymentMeansCode/@name may exist in a UBL invoice or credit note.

**Comment by oriol** [comment]
See comment in #105
