### ISSUE TITLE
The mappning of remittance information [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#107]
BG-16 Payment instructions has cardinality 0..1 and BT-83 Remittance information has cardinality 0..1. Through the syntax binding to UBL, BT-83 is mapped to PaymentID in PaymentMeans, where PaymentMeans has cardinality 0..n.

In line with the specification in EN, multiple occurrences of PaymentMeans may exist in case the transaction is to generate payment via credit transfer (BG-17). 

Request: A validation rule is needed to secure that at most one value for PaymentID may exist in a UBL invoice or credit note.

**Comment by oriol** [comment]
Added rule UBL-SR-44 to solve this issue
