### ISSUE TITLE
The mappning of payment due date [UBL binding to Credit note]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#108]
BT-9, Payment due date, has cardinality 0..1 in the EN. Through the syntax binding to UBL credit note, BT-9 is mapped to PaymentDueDate in PaymentMeans, where PaymentMeans has cardinality 0..n.

In line with the specification in EN, multiple occurrences of PaymentMeans may exist in case the credit note may give raise to payment via credit transfer (BG-17).

Request: A validation rule is needed to secure that at most one value PaymentDueDate may exist in a UBL credit note.

**Comment by oriol** [comment]
added rule UBL-SR-45
