### ISSUE TITLE
AllowanceCharge/ChargeIndicator - binary or not? [UBL mapping]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#110]
The documented values for ChargeIndicator are true/false. But as ChargeIndicator is a simple type Boolean, also values 0 and 1 may be entered without any validation error. 

However, if 0 or 1 is used as ChargeIndicator in BIS Billing 3.0 the calculation formulas fail.

	<cac:AllowanceCharge>
		<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
		<cbc:AllowanceChargeReasonCode>95</cbc:AllowanceChargeReasonCode>
		<cbc:Amount currencyID="SEK">2</cbc:Amount>
		<cac:TaxCategory>
			<cbc:ID>S</cbc:ID>
			<cbc:Percent>25</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:TaxCategory>
	</cac:AllowanceCharge>
	<cac:AllowanceCharge>

		<cbc:ChargeIndicator>0</cbc:ChargeIndicator>
		<cbc:AllowanceChargeReasonCode>95</cbc:AllowanceChargeReasonCode>
		<cbc:Amount currencyID="SEK">2</cbc:Amount>
		<cac:TaxCategory>
			<cbc:ID>S</cbc:ID>
			<cbc:Percent>25</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:TaxCategory>
	</cac:AllowanceCharge>

Request: 
•	Either generate validation error if values 0 or 1 is encountered as ChargeIndicator 
•	Or fix the calculation formulas to recognize 0 and 1 as alternatives to false and true, respectively.

**Comment by oriol** [comment]
Change comparison from literals 'false' and 'true' to functions false() and true()
