### ISSUE TITLE
The UBL version used for binding of the EN data model to UBL

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#111]
As a general principle, information in excess of the EN should be spotted. 
In the current UBL binding, element UBLVersionID may be present (with any value), or omitted, without any validation rule firing. 

It may be argued that UBLVersionID is merely a syntactical element, as it is not reflecting on any business term in the EN, but it does not give a user assurance of control if no policy, and no mechanism (i.e. validation rule), is in place to control its use. 

May it even be that syntax versions later than version 2.1 (which was used for the EN to UBL mapping) may introduce syntactical elements that can carry excess information without being identified as such by the current set of validation rules?

Request: Add a validation rule for UBLVersionID.

**Comment by oriol** [comment]
Should there be a rule excluding the UBLVersionID

**Comment by SLennartsson** [comment]
Hi 

- On the EN side:
True, 16931-1 does not mention UBL, and even less so any particular version of UBL.
But how about 16931-2 and 16931-3-2? 

- On the OASIS UBL TC side:
As UBLVersionID was deemed relevant by the UBL TC, EN implementers have 2 options: use the element or obtain invariant guarantee regarding histoic & future UBL versions.

/Sören
