### ISSUE TITLE
Referencing preceding invoices [UBL, potentially also CII?]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#112]
BT-26 Preceding invoice issue date (BillingReference/InvoiceDocumentReference/IssueDate), if present, should be no later than the issue BT-2 Invoice issue date (IssueDate). 

The following excerpt would not trigger any validation signal:
```xml
…
	<cbc:ID>2018210</cbc:ID>
	<cbc:IssueDate>2018-02-08</cbc:IssueDate>
	<cbc:DueDate>2018-03-07</cbc:DueDate>
	<cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>
…
	<cac:BillingReference>
		<cac:InvoiceDocumentReference>
			<cbc:ID>Preceding invoice no.1</cbc:ID>
			<cbc:IssueDate>2029-12-31</cbc:IssueDate>
		</cac:InvoiceDocumentReference>
	</cac:BillingReference>
…
```

Request: Add a new validation rule (fatal).

**Comment by oriol** [comment]
This rule is not defined by the EN.

**Comment by MartinForsberg-Ecru** [comment]
One could argue that "preceding" means "before"... :)

**Comment by SiwMeckelborg** [comment]
The updated rule should allow Preceding invoice date to be **equal to** or earlier then, now it cannot be the same date.

**Comment by oriol** [comment]
As this new rule (BR-58) is not clearly and explicitly identified in the EN (even if you can derive it from the text of the Norm) we will wait for a revision of the EN to include such a BR. In the meantime, this rule can be added in the CIUSes.
