### ISSUE TITLE
The checking of names identifying various parties 

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#113]
The binding of EN to UBL carries over too few of the rules in the norm, regarding the naming principles. This applies also to the distinction between the seller’s and the tax representative’s respective VAT numbers.  

<See attached Word document showing requirements on name use in the EN>

Request: Add validation rules as indicated in the EN.

[Re Requirements on name use.docx](https://github.com/CenPC434/validation/files/2856934/Re.Requirements.on.name.use.docx)

**Comment by oriol** [comment]
In EN 16931-1 data   model | In the UBL binding
-- | --
BT-28, Seller   trading name, has usage note “This may be used if different from the Seller   name” | No rule to assess if   a party’s   PartyName/Name   differs from its   PartyLegalEntity/RegistrationName
BT-45, Buyer trading   name, has the usage note “This may be used if different from the Buyer name.” | No rule to assess if   a party’s   PartyName/Name   differs from its   PartyLegalEntity/RegistrationName
BG-12, Seller tax   representative, has usage note “The Seller tax representative name/postal   address shall be provided in the invoice, if the Seller has a tax   representative who is liable to pay the VAT due. Sufficient components of the   address are to be filled to comply with legal requirements.”    As tax   representative is a party/role separate from the seller, this implies that   both the name and the VAT number of the tax representative is different from   those of the seller. | No rule to assess if   PartyName/Name of the tax representative differs from the seller’s formal and   trading names.       No rule to assess if   the VAT number of the tax representative differs from (any) VAT number of the   seller.
BT-70, Deliver to   name, has usage note “Shall be used if the Deliver to party is different from   the Buyer.” | No rule to assess if   the delivery party’s   PartyName/Name   differs from formal and trading names of the buyer.

**Comment by oriol** [comment]
Adding business rules comparing string texts could raise false positives when names are  not strictly added in the same way. 

I would suggest not creating those rules.
