### ISSUE TITLE
Incorrect formula(s) when mixed tax rates have to be reported in TaxTotal [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#116]
In Sweden invoices may contain more than one tax rate (6%, 12% and/or 25%), all regarded as TaxCategory=”S”. Also the combination of TaxCategories ”S” and “E” is possible. All occurrencies of these tax combinations must be presented within TaxTotal as TaxSubTotals in the invoice. 

EN 16931-1 illustrates situations of this nature in sections A.1.2 Example 1 and A.1.8 Example 7. 

Currently, for “standard tax” the reporting of tax in TaxTotal seems to fail if more than one tax rate is present. Examples to failure are: When TaxableAmount=0
- A TaxCategory-VAT rate combination may exist in a TaxSubTotal without any corresponding cost component on invoice line or as allowance or charge on document level 
- A TaxCategory-VAT rate combination may exist as a cost component on invoice line or as allowance or charge o document level without any corresponding TaxSubTotal 

See attached test files. 

Request: Review the set of rules validation to secure the following:
- Any combination of TaxCategory and VAT rate that is present on invoice line or as allowance or charge on document level must also be present in a TaxSubTotal
- Any combination of TaxCategory and VAT rate that is present in a TaxSubTotal must also be present on invoice line or as allowance or charge on document level 
- For each combination of TaxCategory and VAT rate in the invoice (credit note), the TaxSubTotal/TaxableAmount must be equal to the sum of LineExtensionAmounts plus charge amount on document level minus allowance amount on document level, where all have identical TaxCategory and VAT rate.

[Incorrect_VATBreakdown_XML_usecase.pdf](https://github.com/CenPC434/validation/files/2866616/Incorrect_VATBreakdown_XML_usecase.pdf)
[Incorrect_VATBreakdown_with_SFTI_sylesheet.pdf](https://github.com/CenPC434/validation/files/2866617/Incorrect_VATBreakdown_with_SFTI_sylesheet.pdf)

**Comment by SiwMeckelborg** [comment]
I agree this should be fixed, and that the example should generate an error, but I am questioning the way this is solved. Is it ok to add 2 new rules which does not have a corresponding Business rule in the EN? (particularly since the rule id seems to reflect these are business rules from the EN (BR-66 and BR-67)

**Comment by oriol** [comment]
How would you solve the issue then?

**Comment by SiwMeckelborg** [comment]
I hoped you had a good answer to that...:) I see two possible options: 
1) Use/rewrite the BR-S-08 rule, to ensure it checks this
2) In the rule text of your new rules reference chapter "6.4.3.3.1 Standard rate and reduced rate items" and its last bullet point where the following text appears: "In the calculation of VAT the Invoice shall show a subtotal of the VAT taxable amount and the VAT tax amount for each VAT rate (i.e. each combination of the category code S and VAT tax rate on line level and for allowance and charges on document level)."

**Comment by oriol** [comment]
Suggestion:
- To include the check in rule BR-S-08 that there is an invoice line or allowance category code that actually has the percentage in the TaxTotal TaxSubtotal TaxCategory.

- To maintain rule BR-66¡ checking that each percent found at line or allowance level is summed up in the totals, adding the text you refer in point 2.

**Comment by oriol** [comment]
BR-67 to be removed because it is not explicitly defined in the EN.

**Comment by oriol** [comment]
BR-66 is also removed as this rule is not explicitly defined in the EN. 

It can be implemented in the CIUS and added in another release of the European Norm.
