### ISSUE TITLE
Non-negative MultiplierFactorNumeric [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#117]
It would be wise to introduce a validation rule saying that MultiplierFactorNumeric (percentage) is to be non-negative, applying to Invoice/AllowanceCharge as well as Invoice/InvoiceLine/AllowanceCharge. This would block unwanted constructs like the strange ones shown below. 

This proposal should be assessed in the context of EN 16931 data model, where a strict separation is maintained between allowances and charges. Additionally, the allowance reason codes and charge reason codes, respectively, are drawn from separate code lists.

Exhibit 1 – The normal way to express a charge:
```xml
<cac:AllowanceCharge> 
	<cbc:ChargeIndicator>true</cbc:ChargeIndicator>
	<cbc:AllowanceChargeReasonCode>WH</cbc:AllowanceChargeReasonCode>
	<cbc:AllowanceChargeReason>Warehousing</cbc:AllowanceChargeReason>
	<cbc:MultiplierFactorNumeric>60</cbc:MultiplierFactorNumeric>
	<cbc:Amount currencyID="SEK">6000</cbc:Amount>
	<cbc:BaseAmount currencyID="SEK">10000</cbc:BaseAmount>
</cac:AllowanceCharge>
```

Exhibit 2 – The strange way to express a charge – it should be blocked:
```xml
<cac:AllowanceCharge> 
	<cbc:ChargeIndicator>true</cbc:ChargeIndicator>                              <!-- Indicates charge -->
	<cbc:AllowanceChargeReasonCode>WH</cbc:AllowanceChargeReasonCode>
	<cbc:AllowanceChargeReason>Warehousing</cbc:AllowanceChargeReason>
	<cbc:MultiplierFactorNumeric>-60</cbc:MultiplierFactorNumeric> <!--Negative amount -->
	<cbc:Amount currencyID="SEK">6000</cbc:Amount>                        <!-- Positive amount -->
	<cbc:BaseAmount currencyID="SEK">-10000</cbc:BaseAmount>    <!-- Negative amount -->
</cac:AllowanceCharge>
```

Exhibit 3 – The even stranger way to express a charge – it should be blocked:
```xml
<cac:AllowanceCharge>  
	<cbc:ChargeIndicator>false</cbc:ChargeIndicator>                        <!-- Indicates allowance -->
	<cbc:AllowanceChargeReasonCode>95</cbc:AllowanceChargeReasonCode>
	<cbc:AllowanceChargeReason>Discount</cbc:AllowanceChargeReason>
	<cbc:MultiplierFactorNumeric>-40</cbc:MultiplierFactorNumeric> <!--Negative amount -->
	<cbc:Amount currencyID="SEK">-4000</cbc:Amount>                       <!--Negative amount -->
	<cbc:BaseAmount currencyID="SEK">10000</cbc:BaseAmount>     <!-- Positive amount -->
</cac:AllowanceCharge>
```

NB! Do not be tempted to introduce rules on non-negative values for elements Amount and BaseAmount in class AllowanceCharge. The validation rules have to recognise the fact that invoices may be corrected either via negative invoice or via credit note.

Request: Validation rule securing that MultiplierFactorNumeric is non-negative (fatal)

**Comment by oriol** [comment]
This is not a rule in the EN. The validation artefacts should not go beyond the EN itself.

This may need discussion in the TC434 and then, once agreed, be added as a rule in the validation artefacts.

**Comment by SLennartsson** [comment]
Hi

The keenness of the EN authors to separate between BG-20, BG-27 and BT-147 on the one side and BG-21 and BG-28 on the other, in itself implies a rule that should not be easily circumvented.  

Section A.3.2.1, 1st paragraph, comments on their meaning; if still deemed linguistically unclear common practice should be to consult CEN’s  English dictionary of preference.

/Sören

**Comment by oriol** [comment]
Agreed during the WG3 cc to delegate this to WG1 in TC434
