### ISSUE TITLE
Non-negative discount in InvoiceLine/Price [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#118]
BT-147, Item price discount, has description “The total discount subtracted from the Item gross price to calculate the Item net price”. BIS Billing 3.0 would need validation rule(s) to make sure that the discount restriction is respected – I attach snippets that are currently accepted when validating. 
(Note – As it applies to the price component, the “discount rule” should be the same in invoices as well as in credit notes as well as in negative invoices.)

Exhibit 1 – A strange discount (calculation of net price validated) – should be blocked:
```xml
<cac:Price>
	<cbc:PriceAmount currencyID="SEK">5</cbc:PriceAmount>    <!-- BT-146, Item net price   -->    
	<cbc:BaseQuantity unitCode="EA">2</cbc:BaseQuantity>
	<cac:AllowanceCharge>                                       
		<cbc:ChargeIndicator>false</cbc:ChargeIndicator>   <!-- Only discount allowed -->
	  	<cbc:Amount currencyID="SEK">-5</cbc:Amount>    <!-- BT-147, negative discount -->
		<cbc:BaseAmount currencyID="SEK">0</cbc:BaseAmount> <!-- BT-148 gross price -->
	</cac:AllowanceCharge>
</cac:Price>
```

Exhibit 2 – A strange discount (no net price validation) – should be blocked:
```xml
<cac:Price>
	<cbc:PriceAmount currencyID="SEK">25</cbc:PriceAmount>  <!-- BT-146, Item net price   -->    
	<cbc:BaseQuantity unitCode="EA">1</cbc:BaseQuantity>
	<cac:AllowanceCharge>                                       
		<cbc:ChargeIndicator>false</cbc:ChargeIndicator>    <!-- Only discount allowed -->  			<cbc:Amount currencyID="SEK">-0</cbc:Amount>     <!-- BT-147 negative discount -->
	</cac:AllowanceCharge>
</cac:Price>
```

Request: BT-147, represented by AllowanceCharge/Amount, to be blocked if negative (fatal)

**Comment by oriol** [comment]
This is not a rule in the EN. The validation artefacts should not go beyond the EN itself.

This may need discussion in the TC434 and then, once agreed, be added as a rule in the validation artefacts.

**Comment by oriol** [comment]
Discussed in TC434 and agreed that this has to be discussed in TC434 WG1
