### ISSUE TITLE
Error in validation BR-CO-17 and BR-S-09

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#120]
This issue was reported to PEPPOL. I'm adding it here as it relates to EN validation rules.

There seems to be an error in CEN-EN16931-UBL schematron for BR-CO-17 and BR-S-09.

The validation of the VAT category tax amount (BT-117) are valid for a positive invoice but not for the same negative amounts in a negative invoice.

[POACC-187.zip](https://github.com/CenPC434/validation/files/2919231/POACC-187.zip)

**Comment by oriol** [comment]
used abs function in BR-S-09
