### ISSUE TITLE
VAT-identifier mandatory for customer if supplier is not subject to VAT

### ISSUE THREAD

**Issue by SimonsPaul** [ConnectingEurope/eInvoicing-EN16931#121]
Hi,
This test is not correct in my opinion.
Location: `UBLBE_BE0000000196_V01-15000022.xml`
Element/context: `/Invoice
XPath test: (exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'O']) and (not(//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VAT']/cbc:CompanyID) and not(//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VAT']/cbc:CompanyID) and not(//cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VAT']/cbc:CompanyID))) or not(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'O'])`

Error message: `[BR-O-02]-An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is “Not subject to VAT” shall not contain the Seller VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) or the Buyer VAT identifier (BT-46).`

If a non profit organisation that is invoicing services not subject to VAT to a company that is subject to VAT, the VAT number of the receiver has to be mentioned on the invoice.

**Comment by oriol** [comment]
To be discussed in WG1 of TC434
