### ISSUE TITLE
BR-S-08 causes validation to crash when more than one TaxCategory

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#124]
The rule BR-S-08 is expecting that only one ClassifiedTaxCategory is provided on line-level. However, according to the UBL-schema, this element can be repeated. When repeated the XPATH/test in the rule will not work and result in an exception.

The rule causes the complete transformation (when using xslt for execution) to fail and the user will not see what went wrong.

Solutions:
Fix the rule so that it only acts on the first repetition. (there are probably more rules with similar issue)
Or
Separate the syntax rules into its own schematron file where all checks of cardinality and so on takes place. That way this module will report errors without failing and the user can figure out what is wrong.

**Comment by oriol** [comment]
can you check whether this issue is resolved now?

**Comment by oriol** [comment]
the crash was due to the fact that the normalize-space was done in a wrong place. Now this has been fixed and should not fail.
