### ISSUE TITLE
BT-90 mapping in ubl

### ISSUE THREAD

**Issue by sarafacchinettiIC** [ConnectingEurope/eInvoicing-EN16931#126]
As alredy discussed in https://github.com/CenPC434/validation/issues/104 and https://github.com/CenPC434/validation/issues/92 

Could BT-90 be mapped to 
`Invoice/cac:PaymentMeans/cac:PaymentMandate/cac:PayeeFinancialAccount/cbc:ID`?

**Comment by oriol** [comment]
In the validation rules we cannot change changes in the syntax binding. This has to be done within the TC434

**Comment by oriol** [comment]
Discussed. Must be agreed in the TC 434.

**Comment by oriol** [comment]
Reopen the issue as it is not closed, but it is not to be implemented in a validation artefact but in the TC434 WG3.
