### ISSUE TITLE
BR-CO-03 CII schematron

### ISSUE THREAD

**Issue by sarafacchinettiIC** [ConnectingEurope/eInvoicing-EN16931#129]
Is the rule BR-CO-03 properly working?

![image](https://user-images.githubusercontent.com/45999456/55612019-80865700-5787-11e9-9c64-5c11861988cf.png)

This code shall not be correct
![image](https://user-images.githubusercontent.com/45999456/55612285-2afe7a00-5788-11e9-8688-12f67a1801d9.png)

**Comment by oriol** [comment]
the rule is looking for the BT-7 and BT-8 not in the same BG-23 group.

**Comment by sarafacchinettiIC** [comment]
Yes, but BT-7 and BT-8 in the semantic model are at invoice level with 0..1 cardinality. One BT-7 mutually exclusive with one BT-8
