### ISSUE TITLE
CountryCodes ISO 3166-1

### ISSUE THREAD

**Issue by CSkovhus** [ConnectingEurope/eInvoicing-EN16931#130]
The code "RE" (Réunion) is in the code list (http://docs.peppol.eu/poacc/billing/3.0/codelist/ISO3166/) but it is not in the schematron (CEN-EN16931-UBL).

      <rule context="cac:Country/cbc:IdentificationCode" flag="fatal">
         <assert test="((not(contains(normalize-space(.), ' ')) and contains(' AD AE AF AG AI AL AM AN AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BL BJ BM BN BO BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR ST SV SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW ', concat(' ', normalize-space(.), ' '))))"
                 id="BR-CL-14"
                 flag="fatal">[BR-CL-14]-Country codes in an invoice MUST be coded using ISO code list 3166-1</assert>
      </rule>

**Comment by sarafacchinettiIC** [comment]
See https://github.com/CenPC434/validation/issues/91, I believe it is solved in this github (in ubl at least, perhaps still not in https://github.com/CenPC434/validation/blob/master/cii/schematron/codelist/EN16931-CII-codes.sch )

**Comment by oriol** [comment]
added in CII
