### ISSUE TITLE
Add slack in calculation rules 

### ISSUE THREAD

**Issue by oriol** [ConnectingEurope/eInvoicing-EN16931#131]
Up to 50% of invoices are having faults due to a slack when rounding. 

The slack is small but more than 0 that is the requirement in the EN today.
Is there a possibility to have a slack of "1" when rounding?

For not losing electronic invoices when upgrading to the EN, I ask WP3 to find a solution so that this issue can be resolved quickly since the directive on the EN is mandatory from April 18th.

Affected rules are:

**[BR-CO-15]**-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).
**[BR-CO-16]**-Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Paid amount (BT-113) +Rounding amount (BT-114).
**[BR-CO-17]**-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.

**[BR-IG-08]**-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "IGIC", the VAT category taxable amount (BT-116) in a VATBReakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "IGIC" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).
**[BR-IG-09]**-The VAT category tax amount (BT-117) in a VATBReakdown (BG-23) where VAT category code (BT-118) is "IGIC" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119).
**[BR-IP-08]**-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "IPSI", the VAT category taxable amount (BT-116) in a VATBReakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "IPSI" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).
**[BR-IP-09]**-The VAT category tax amount (BT-117) in a VATBReakdown (BG-23) where VAT category code (BT-118) is "IPSI" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119).
**[BR-S-08]**-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "Standard rated", the VAT category taxable amount (BT-116) in a VATBReakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "Standard rated" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).
**[BR-S-09]**-The VAT category tax amount (BT-117) in a VATBReakdown (BG-23) where VAT category code (BT-118) is "Standard rated" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119).<

**Comment by oriol** [comment]
Does **BR-CO-16** need to have an slack added ? It already contains the PayableRoundingAmount that can be used to avoid rounding problems.

**Comment by oriol** [comment]
Decision WG3. 

Slack of 1
Not apply to BR-CO-15
Apply to CII

**Comment by oriol** [comment]
CII users have not reported the need for a slack on their calculation rules.

**Comment by svanteschubert** [comment]
@oriol Can you provide CEN/TC 434 members with a reference to the incorrect files for analysis and testing?
