### ISSUE TITLE
BT-84 CII mapping

### ISSUE THREAD

**Issue by sarafacchinettiIC** [ConnectingEurope/eInvoicing-EN16931#132]
BT-84 can be mapped to two different tags
`/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeePartyCreditorFinancialAccount/ram:IBANID`

or
`/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeePartyCreditorFinancialAccount/ram:ProprietaryID`

Perhaps a rule to check that they are mutually exclusive should exist in CII schematron
This code shall not be possible as BT-84 cardinality is 1..1
![image](https://user-images.githubusercontent.com/45999456/55810875-8910c180-5ae8-11e9-83b5-e0ed052e6823.png)

**Comment by oriol** [comment]
Not a validation artefact issue but a syntax binding. Bring to TC 434 WG3.
