### ISSUE TITLE
CII validation of XSLT does not work

### ISSUE THREAD

**Issue by svanteschubert** [ConnectingEurope/eInvoicing-EN16931#139]
There is an error during the validation phase of the current generated XSLT.
The generation of XSLT is done via `mvn -f pom-xslt.xml process-resources`, the validation of the examples by the new XSLT is done via `mvn -f pom-validate.xml validate`

When I take a look between my last commit and the ones of Philip (we both test before commit), there are the following changes:
https://github.com/CenPC434/validation/compare/71ff4f3..2063375
(This comparison URL was created by hand to get advantage of the nice GitHub diff view)

One change is interesting:
OLD:
`<param name="BR-56" value="(ram:SpecifiedTaxRegistration/ram:ID[@schemeID='VAT']!='')"/>`
NEW:
`<param name="BR-56" value="(ram:SpecifiedTaxRegistration/ram:ID[@schemeID='VA']!='')"/>`

While the CII_example1.xml test file that causes the problem does contain the following:
<ram:ID schemeID="VAT">NL8200.98.395.B.01</ram:ID>

Please trigger the tests before committing! :-)

**Comment by phax** [comment]
@oriol  Shouldn't we create the Schematrons in a way, that both "VA" and "VAT" is accepted (for backwards compatibility to the 1.1.0 release)?

**Comment by svanteschubert** [comment]
I have been using the last mapping specification that I was able receive. If 'VAT' is correct in the very latest revision, I suggest we should fix it to 'VAT' and provide - if at all - a comment that 'VA' was mentioned prior by incident. I would suggest to avoid the extra burden and complexity to add various branches for various releases, while there is only one final truth we are striving to. In addition, the goal of the validation artefacts is to show the user in the end any errors in the documents (independent if they have been already published or not)...

**Comment by oriol** [comment]
it was agreed in the Reykjavik meeting to stick to the Norm, that’s why we need to use VA in certain cases and VAT in others.



Enviat des del meu iPhone

El 17 abr 2019, a les 16:50, Svante <notifications@github.com> va escriure:

**Comment by phax** [comment]
Is there already a release date for the CiI corrigendum?
