### ISSUE TITLE
Rounding on invoice lines and [BR-CO-17] rule

### ISSUE THREAD

**Issue by kamilpiotrkowski** [ConnectingEurope/eInvoicing-EN16931#143]
I have a problem with the following validation rule ([BR-CO-17]):

[BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals for transformation to EHF 3

On some invoice lines (InvoiceLine\TaxTotal) appear rounding of 0,01 NOK on TaxAmount. For example, on the following line:
```xml
  <cac:InvoiceLine>
    <cbc:ID>1</cbc:ID>
    <cbc:InvoicedQuantity unitCode="xx" unitCodeListID="xx">2</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="NOK">696.22</cbc:LineExtensionAmount>
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="NOK">174.06</cbc:TaxAmount>
    </cac:TaxTotal>
    <cac:Item>
      <cbc:Name>Item name</cbc:Name>
      <cac:ClassifiedTaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="NOK">348.11</cbc:PriceAmount>
    </cac:Price>
  </cac:InvoiceLine>
```
  
 (2*348,11) * 0,25 = 174,055 ~ 174,06
 
When I have more such lines, the total tax amount in TaxTotal\TaxAmount node does not pass validation [BR-CO-17] rule because the amount contains rounding.

```
(xs:decimal(cbc:TaxAmount) = round(xs:decimal(cbc:TaxableAmount) * (cac:TaxCategory/xs:decimal(cbc:Percent) div 100) * 10 * 10) div 100 ))
```

How I should handle rounding so that the rule can be met?

**Comment by MartinForsberg-Ecru** [comment]
TaxTotal on line level isn't used in the EN. The SubTotals on header level are calculated based on the sum of taxable amounts of the lines for each rate.

**Comment by oriol** [comment]
Agree with Martin, this rule should only fire at header level, not at line level.

**Comment by kamilpiotrkowski** [comment]
Yes, I mean header level.

Tax from each line is placed in TaxTotal\TaxSubtotal node at header level.

I have two invoice lines:  (348.11*2)*0,25 = 174,055 ~ 174,06

This two lines gives me on header level:
TaxTotal\TaxableAmount = 1392.44
TaxTotal\TaxSubtotal\TaxAmount = 348.12
TaxTotal\TaxSubtotal\TaxCategory\Percent

This rule [BR-CO-17] calculate (in simplification): 1392.44 * 0,25 = 348.11 and reports an error because the amount does not match with TaxTotal\TaxSubtotal\TaxAmount = 348.12 due to rounding from invoice lines (0.01 NOK from both lines).
 
**For example:**

_Invoice lines:_

```    <cac:InvoiceLine>
    <cbc:ID>1</cbc:ID>
    <cbc:InvoicedQuantity unitCode="xx" unitCodeListID="xx">2</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="NOK">696.22</cbc:LineExtensionAmount>
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="NOK">174.06</cbc:TaxAmount>
    </cac:TaxTotal>
    <cac:Item>
      <cbc:Name>Item name</cbc:Name>
      <cac:ClassifiedTaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="NOK">348.11</cbc:PriceAmount>
    </cac:Price>
  </cac:InvoiceLine>
    <cac:InvoiceLine>
    <cbc:ID>2</cbc:ID>
    <cbc:InvoicedQuantity unitCode="xx" unitCodeListID="xx">2</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="NOK">696.22</cbc:LineExtensionAmount>
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="NOK">174.06</cbc:TaxAmount>
    </cac:TaxTotal>
    <cac:Item>
      <cbc:Name>Item name</cbc:Name>
      <cac:ClassifiedTaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="NOK">348.11</cbc:PriceAmount>
    </cac:Price>
  </cac:InvoiceLine>````

_Header:_

```  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="NOK">348.12</cbc:TaxAmount>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="NOK">1392.44</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="NOK">348.12</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID schemeID="UNCL5305">S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:TaxCategory>
    </cac:TaxSubtotal>
  </cac:TaxTotal>```

**Comment by MartinForsberg-Ecru** [comment]
In your example, you have the element TaxTotal/TaxAmount on line level. This isn't correct as the european standard only have rates (no tax amounts) on line level. So the SubTotal on header is the sum of tax for each rate. Calculated as "(Sum of LineExtension amount for each rate) * rate"
