### ISSUE TITLE
Unify names of "entry" files

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#146]
The UBL file is called "EN16931-UBL-model.sch" whereas in CII the file is called "EN16931-CII-validation.sch" and in EDIFACT it is labeled "EN16931-EDIFACT-validation.sch".

I suggest we go for the unique naming "EN16931-`syntax`-validation.sch". That will be propagated to the XSLT as well of course

**Comment by oriol** [comment]
Agree with your proposal
