### ISSUE TITLE
Consistent naming of release assets

### ISSUE THREAD

**Issue by rkottmann** [ConnectingEurope/eInvoicing-EN16931#149]
The UBL and CII assets in release 1.0.0 and 1.1.0 were named “en16931-[cii|ubl]-major.minor.patch.zip. In release 1.2.0 the dots were omitted. Since we automatically download and process the assets, consistent naming is helpful and thus important. Please add the missing dots to the asset names in release 1.2.0.

**Comment by phax** [comment]
Fixed. Thx for pointing that out.

**Comment by rkottmann** [comment]
That was super fast 😄 👍
