### ISSUE TITLE
Payment ID must be allowed to occur more than once (UBL-SR-44)

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#150]
Due to the fact that PaymentMeans can be repeated, the implementation of this rule should be changed:

[UBL-SR-44]-Payment ID shall occur maximum once

It should however check that PaymentID must have the same value for each repetition.

**Comment by phax** [comment]
I stumbled upon the same issue. It happens in the CII examples files 1.2.0

**Comment by oriol** [comment]
Could we release a 1.2.1 with this corrected?

**Comment by phax** [comment]
Sure. There is also an issue from Siw...

**Comment by MartinForsberg-Ecru** [comment]
The current implementation of the rule only works when 1 or 2 payment means are used. If you have a third payment means, with identicial PaymentID, the rule still fires.

**Comment by oriol** [comment]
The binding to UBL only allows for two repetitions of the PaymentMeans class. Having this into account, the rule should fire if there is a third repetition.

**Comment by MartinForsberg-Ecru** [comment]
I don't see where the binding says only two repetitions are allowed. As the Credit Transfer group in the semantic model is 0..n but the PayeeFinancialAccount is 0..1 in UBL, the solution was to repeat the whole PaymentMeans-element. With the consequence that the type and remittance information (PaymentID) must be identical for each repetition.

**Comment by SiwMeckelborg** [comment]
This rule does not fire for Credit notes, in fact it seems none of the Syntax specific rules fire for Credit Notes, only invoices (looking at the rule context in the preprocessed Schematron)

**Comment by phax** [comment]
@SiwMeckelborg do you depend on the "preprocessed" Schematron files? If so, please retest, since the files were just updated recently

**Comment by SiwMeckelborg** [comment]
Test ok
