### ISSUE TITLE
BT-132 no check on existence BT-13  

### ISSUE THREAD

**Issue by WvandenBerg** [ConnectingEurope/eInvoicing-EN16931#154]
BT-13 = Purchase order reference
BT-132 = Referenced purchase order line reference 

As far as I can tell, there currently is no rule that specifies BT-13 is mandatory when BT-132 is used on invoice line level. There probably should be. All I could find was a usage note for BT-132 that says: "The purchase order identifier is referenced on document level.". Of course, being a usage note, all it does is imply such a rule.

**Comment by oriol** [comment]
Only the business rules explicitly identified in the EN will be implemented in this validation artefact rule set.

These rules can be implemented in the CIUSes.
