### ISSUE TITLE
TaxScheme/ID does not perform normalize space

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#155]
Some or most of the rules checking the existence of TaxScheme/ID='VAT' will fire if elemement content is '  VAT', i.e it does not strip blank spaces, I think it should?

**Comment by oriol** [comment]
added normalize-space in functions checking the VAT

**Comment by kosek** [comment]
TaxScheme/ID is derived from xs:normalizedString - this datatype does much less aggressive whitespace  normalization then normalize-space() function. It just normalizes CR and LF characters to space (see https://www.w3.org/TR/xmlschema-2/#normalizedString)

So the correct fix would be to use custom function based on replace() to do the same kind of normalization. Or not do any normalization at all. See related issue with the detailed analysis of this https://github.com/CenPC434/validation/issues/114#issuecomment-483310955

**Comment by oriol** [comment]
Adding a blank in the ID (' VAT') does not raise any error in the XSD validation, and it raises Schematron errors when it should not.

**Comment by kosek** [comment]
But XSD doesn't have codelist defined for this value so it can not produce any error.

**Comment by phax** [comment]
Because Schematron does not use the XSD type system (correctly)

**Comment by oriol** [comment]
I will then close the issue again.
