### ISSUE TITLE
Wrong rule context on many of the syntax rules

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#156]
A lot of the UBL syntax rules (examples: UBL-CR-001, UBL-SR-01, UBL-SR-47) only have the ubl:Invoice as context, most of these should be valid for credit note as well I assume?

**Comment by oriol** [comment]
These rules exclude the nodes not in the EN from the Invoice UBL model. Should be checked whether the same nodes are to be excluded from the Credit Note or additional rules shall be created.

**Comment by SiwMeckelborg** [comment]
Seems the preprocessed file does not have these changes included

**Comment by phax** [comment]
I will update XSLT and preprocessed files now

**Comment by phax** [comment]
Updated through https://github.com/CenPC434/validation/commit/ca7e6630b0c80809597d1438c05b249bf3a4b44e

**Comment by phax** [comment]
@SiwMeckelborg please re-test

**Comment by SiwMeckelborg** [comment]
The rule context for the syntax rules are  
    `<rule context="/ubl:Invoice | /ubl:CreditNote">`
According to the namespace declarations it should be `cn:CreditNote`
