### ISSUE TITLE
rule BR-O-04

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#157]
Following issue was reported by manuela.citrigno@regione.emilia-romagna.it to PEPPOL help desk through issue POACC-200 and is herewith escalated to TC434, closing the issue on PEPPOL side.

The rule (http://docs.peppol.eu/poacc/billing/3.0/rules/BR-O-04/) restricts only document level charges (BG-21), but the schematron test is actually considering all charges:
//cac:AllowanceCharge[cbc:ChargeIndicator='true']... (mind double slash!)
so fails also if an invoice contains Line level charge (GB-28) and does contain VAT identifiers for Seller or Buyer.
I think the correct test would be:

(exists(/ubl:Invoice/cac:AllowanceCharge[cbc:ChargeIndicator='true']/cac:TaxCategory[normalize-space(cbc:ID) = 'O']) and (not(//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VAT']/cbc:CompanyID) and not(//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VAT']/cbc:CompanyID) and not(//cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VAT']/cbc:CompanyID))) or not(exists(/ubl:Invoice/cac:AllowanceCharge[cbc:ChargeIndicator='true']/cac:TaxCategory[normalize-space(cbc:ID) = 'O']))

**Comment by oriol** [comment]
Cannot use ubl:Invoice because the context is both ubl:Invoice or cn:CreditNote

**Comment by phax** [comment]
But a rule with context `[/ubl:Invoice|/ubl:CreditNote]`  could work right?

**Comment by oriol** [comment]
almost :)

**Comment by oriol** [comment]
the same issue can be found in BR-O-03.
