### ISSUE TITLE
Rule BR-O-08 - wrong context

### ISSUE THREAD

**Issue by jarekglapski** [ConnectingEurope/eInvoicing-EN16931#159]
Context for rule BR-O-08 (cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory[normalize-space(cbc:ID) = 'O']) seems to be too wide and matches also line level line level tax breakdown if such is given. When it matches, the assertion must fail. I understand that line level tax breakdown is not "in use", but it is not forbidden. 
Either the rule should be added to restrict usage of InvoiceLine/TaxTotal/TaxSubtotal breakdown (not sure if a good idea)
Or the context for BR-O-08 shall be: 
(/ubl:Invoice | /cn:CreditNote)/cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory[normalize-space(cbc:ID) = 'O']

**Comment by oriol** [comment]
TaxTotal class shall not be added at line level according to the syntax binding and the EN.

**Comment by jarekglapski** [comment]
Thanks, Does it make sense to enforce it will additional rule then?

Side note (I guess not for this audience, but perhaps you can advise).
I am not sure how to deal with such scenario (real case from France):
A single service is given (to an elevator in a building), but it should be taxed respectively with two different tax rates, because part of the building is used for habitation and the other part for professional services. We wanted to use line level tax breakdown to reflect it properly. Now it looks like we'd have to split invoice line into two separate lines.
Are there any guidelines for such cases?

**Comment by oriol** [comment]
Rule UBL-CR-561 states that "A UBL invoice should not include the InvoiceLine TaxTotal" so this rule should fire when adding tax total at line level.

Regarding your second comment, I guess it shall be addressed to the TC434 but with the current European Norm model, you will have to separate the service in two different invoice lines.
