### ISSUE TITLE
CEF VATEX and related business rules

### ISSUE THREAD

**Issue by AndreasPvd** [ConnectingEurope/eInvoicing-EN16931#161]
Now, that CEF VATEX is available and already partly implemented in these artefacts, shouldn't the corresponding business rules referencing the codelist be updated as well?

Example:

BR-AE-10 states 

> ... shall have a VAT exemption reason code (BT-121), meaning "Reverse Charge"...

So in my opinion this and the other rules should be updated accordingly...

Br,
Andreas

**Comment by oriol** [comment]
Rules affected are:

[BR-AE-10]-A VAT breakdown (BG-23) with VAT Category code (BT-118) "Reverse charge" shall have a VAT exemption reason code (BT-121), meaning "Reverse charge" or the VAT exemption reason text (BT-120) "Reverse charge" (or the equivalent standard text in another language).

[BR-G-10]-A VAT breakdown (BG-23) with the VAT Category code (BT-118) "Export outside the EU" shall have a VAT exemption reason code (BT-121), meaning "Export outside the EU" or the VAT exemption reason text (BT-120) "Export outside the EU" (or the equivalent standard text in another language).

[BR-IC-10]-A VAT breakdown (BG-23) with the VAT Category code (BT-118) "Intra-community supply" shall have a VAT exemption reason code (BT-121), meaning "Intra-community supply" or the VAT exemption reason text (BT-120) "Intra-community supply" (or the equivalent standard text in another language).

[BR-O-10]-A VAT breakdown (BG-23) with VAT Category code (BT-118) " Not subject to VAT" shall have a VAT exemption reason code (BT-121), meaning " Not subject to VAT" or a VAT exemption reason text (BT-120) " Not subject to VAT" (or the equivalent standard text in another language).

Therefore, we would check the following codes in CEF VATEX:

- Reverse charge - vatex-eu-ae
- Export outside the EU - vatex-eu-g
- Intra-community supply - vatex-eu-ic
- Not subject to VAT - vatex-eu-o

**Comment by SiwMeckelborg** [comment]
I have some questions to this resolution, in the VATEX code list there are several different codes available, are we certain no other codes can be used?
Example:  if VAT category = AE, only code "vatex-eu-ae" is allowed.  In the VATEX codelist the following remark is found for this code "Only use with VAT category code AE". 

So should be instead check that if TaxExemptionReasonCode = "vatex-eu-ae", then VAT category must be AE? (And similar for the other codes where this kind of remark is made?)  And how do we handle this as this is a rule enforced by CEF and the VATEX codelist, and is not a EN16931 rule as such

**Comment by oriol** [comment]
We will revert this change and ask CEF for the correspondance between the codes and the VAT category codes
