### ISSUE TITLE
Some tests are not applied for CreditNote type

### ISSUE THREAD

**Issue by jarekglapski** [ConnectingEurope/eInvoicing-EN16931#164]
Some tests, like:
` [UBL-SR-05]-Payment terms shall occur maximum once`
and many more are not applied for CreditNote type, because the corresponding template matches only an Invoice:
`<xsl:template match="/ubl:Invoice" mode="M11" priority="1006">`

According to specs, at least some of them (ex: [UBL-SR-05]) should apply to CreditNotes as well.
I believe, all of them are "warnings", but perhaps it is worth to be refactored anyway.

**Comment by oriol** [comment]
The context has been changed to value="/ubl:Invoice | /cn:CreditNote" so this is resolved.
