### ISSUE TITLE
[BR-S-01] rule catches an extra (unintended?) case

### ISSUE THREAD

**Issue by jarekglapski** [ConnectingEurope/eInvoicing-EN16931#165]
As per the message the rule was intended to catch the case when there is no S category in VAT Breakdown (while there are any S category items or allowances/charges:

> An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is “Standard rated” shall contain in the VATBReakdown (BG-23) at least one VAT category code (BT-118) equal with "Standard rated".

Apparently it covers also the opposite scenario - when there is an S category in VAT Breakdown and no items or allowances/charges to match it.

I guess, this scenario is invalid as well, so no harm that the rule matches it. Perhaps just the message should be rephrased? 

Side note: same may apply to other similar rules for different VAT categories

**Comment by oriol** [comment]
Yes, it catches the opposite scenario on purpose as it is also invalid.  

It is not on the scope of the validation artefacts to rephrase the rules though.
