### ISSUE TITLE
Value added tax point date to be independent of invoicing period

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#168]
In EN 16 931-1, BT-8 Value added tax point date code and BG-14 Invoicing period has no rule of dependence between them.  
With the UBL syntax binding, presence of InvoicePeriod/DescriptionCode currently requires the presence of also StartDate or EndDate or both.
[Invoice-TaxPointDateCode_withoutPeriod.txt](https://github.com/CenPC434/validation/files/3567207/Invoice-TaxPointDateCode_withoutPeriod.txt)

**Comment by oriol** [comment]
Both StartDate and EndDate are optional, so you can add a Value added tax point date without any of them. 

The norm has no rule of dependence nor of independence, so I do not see the need to add any extra rule.

**Comment by SLennartsson** [comment]
Hi
Clarification: I do not seek a new rule, but I have an issue with rule BR-CO-19.
I attach testfile used to get fatal error using the SFTI validation service.
Regards,
Sören

**Comment by oriol** [comment]
You are right, BI-CO-19 should be corrected.
