### ISSUE TITLE
UBL rules: BR-CL-13 fires when valid value

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#17]
BR-CL-13 fires when valid value is used. Codelist check does not seem complete according to latest version of UNCL 4465. Values 98-104 seems missing, in addition to ZZZ

**Comment by oriol** [comment]
http://www.unece.org/fileadmin/DAM/trade/untdid/d15a/tred/tred4465.htm

I am using this code list. Should it be another one?

**Comment by SiwMeckelborg** [comment]
I see we are both wrong... According to the norm, the values for allowances should be from 5189 and for charges the values should be from 7161. Both from d15a it seems
