### ISSUE TITLE
UBL: Just one way of referencing the document per instance of AdditionalDocumentReference

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#172]
BG-24, Additional supporting documents, may refer to a document in either of the following 3 ways: 
- as reference to a known document (i.e. known to both parties); 
- as attachment embedded in the invoice;
- as URL reference to an external document. 
In my understanding the 3 alternatives are to be mutually exclusive. This means that, in the UBL binding, EmbeddedDocumentBinaryObject and ExternalReference never should be present simultaneously in one instance of AdditionalDocumentReference – the validation rule is missing.
[Invoice-Mix_of_documents_in_one_attachment.txt](https://github.com/CenPC434/validation/files/3569108/Invoice-Mix_of_documents_in_one_attachment.txt)

**Comment by oriol** [comment]
This is an interpretation that is not stated in the European Norm.
