### ISSUE TITLE
UBL: One unclear error signal (PEPPOL-EN16931-R044)

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#175]
Due to a previous remark on alternatives for ChargeIndicator – true/false and 1/0 respectively – a change was made in favour of true/false to be the only option. This may be fine, but I have one consequential observation in case the value of ChargeIndicator is mis-spelled.

Excerpt from a UBL message - example 1:
<cac:Price>
     <cbc:PriceAmount currencyID="SEK">400</cbc:PriceAmount> 
     <cac:AllowanceCharge>
          <cbc:ChargeIndicator>fals</cbc:ChargeIndicator> 
          <cbc:Amount currencyID="SEK">40</cbc:Amount>
          <cbc:BaseAmount currencyID="SEK">440</cbc:BaseAmount>
     </cac:AllowanceCharge>
</cac:Price>
This would generate a UBL 2.1 Invoice level error ‘The content "fals" of element <ChargeIndicator> does not match the required simple type. The string "fals" cannot be cast to a boolean’. This signal is correct and easy to understand.

Excerpt from a UBL message - example 2:
<cac:Price>
     <cbc:PriceAmount currencyID="SEK">400</cbc:PriceAmount> 
     <cac:AllowanceCharge>
          <cbc:ChargeIndicator>0</cbc:ChargeIndicator> 
          <cbc:Amount currencyID="SEK">40</cbc:Amount>
          <cbc:BaseAmount currencyID="SEK">440</cbc:BaseAmount>
     </cac:AllowanceCharge>
</cac:Price>
The above would trigger rule PEPPOL-EN16931-R044 with error signal ‘Charge on price level is NOT allowed.’ In this context the signal is incomprehensible, and even more so for those who regard ‘0’ and ‘false’ to represent the same boolean value.

**Comment by oriol** [comment]
What is the suggestion to correct this issue then?

**Comment by SLennartsson** [comment]
Either test AllowanceCharge/ChargeIndicator generally: If value is other than ’true’ or ‘false’ then generate error signal “Only values from value set (’true’ or’ false’) is recognised for element <ChargeIndicator>."  
Or test specifically for Price/AllowanceCharge/ChargeIndicator: If value is other than ‘false’ then generate error signal “Only value ‘false’ is valid for element <ChargeIndicator> in this position of the message”.
Or something similar.

**Comment by oriol** [comment]
This Rule is from PEPPOL, not from the EN 16931, should be corrected by the PEPPOL PoACC team.
