### ISSUE TITLE
Unclear mapping of BT-29, 46, 60, 70

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#178]
Initially reported to OpenPEPPOL as issue POACC-202 by wk@everbinding.nl
https://openpeppol.atlassian.net/browse/POACC-202

The syntax binding for BT-29, BT-46, BT-60 and BT-70 in part 3-3 is unclear the business term is to be bound to two elements this is conditional based on a rule but is unclear and rule seems to be incomplete, ending with an else ...

**Comment by oriol** [comment]
Nothing to be fixed in the validation artefacts.
