### ISSUE TITLE
UBL: Credit transfer, card payment and direct debit must not be mixed

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#181]
EN specifies 3 different options for payment, each having their characterising business terms: credit transfer (BG-17), payment card information (BG-18) and direct debit (BG-19). They represent payment arrangements that cannot co-exist simultaneously in the invoice: 
- BG-17: the buyer is to transfer money to the supplier’s account 
- BG-18: the buyer has already paid by means of a payment card 
- BG-19: the supplier will exercise a mandate to draw money from the buyer's account.

For UBL we need a new rule – with fatal outcome – to assure that PayeeFinancialAccount (representing BG-17), CardAccount (representing BG-18), and PaymentMandate (representing BG-19) are mutually exclusive: 
a) in one and the same occurrence of PaymentMeans.
b) in one and the same occurrence of Invoice (this 2nd component of the test is needed as PaymentMeans may repeat in UBL).
 
Two test cases are attached:
[Invoice-Mix of BG17, BG18, BG19_1.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/3667895/Invoice-Mix.of.BG17.BG18.BG19_1.txt)
[Invoice-Mix of BG17, BG18, BG19_2.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/3667896/Invoice-Mix.of.BG17.BG18.BG19_2.txt)

**Comment by oriol** [comment]
This is not generally true as there can be cases where invoices allow for different types of payment.

There is no explicit statement on that in the EN.
