### ISSUE TITLE
UBL: Card payment information must not be repeated in the document

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#182]
In UBL, PaymentMeans was designated cardinality 0..n to accommodate for more than one than one bank account in the case of BG-17 Credit transfer. But in case BT-18 Payment card applies, EN 16931-1 specifies cardinality 0..1.
Currently an XML schema rule blocks repetition of CardAccount within PaymentMeans, but we additionally need a rule – with fatal outcome – to assure that PaymentMeans is not repeated when CardAccount (representing BG-18) is present in the document.
[Invoice-Repeating_BG-18.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/3667905/Invoice-Repeating_BG-18.txt)

**Comment by oriol** [comment]
Required to check that there can be only one cac:PaymentMeans/cac:CardAccount at maximum.

[BR-66]-An Invoice shall contain maximum one Payment Card account (BG-18)

count(cac:PaymentMeans/cac:CardAccount) <= 1
