### ISSUE TITLE
UBL: Direct debit must not be repeated in the document

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#183]
In UBL, PaymentMeans was designated cardinality 0..n to accommodate for more than one than one bank account in the case of BG-17 Credit transfer. But in case BT-19 Direct debit applies, EN 16931-1 specifies cardinality 0..1.
Currently an XML schema rule blocks repetition of PaymentMandate within PaymentMeans, but we additionally need a rule – with fatal outcome – to assure that PaymentMeans is not repeated when PaymentMandate (representing BG-19) is present in the document.
[Invoice-Repeating_BG-19.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/3667907/Invoice-Repeating_BG-19.txt)

**Comment by oriol** [comment]
Required to check that there can be only one cac:PaymentMeans/cac:PaymentMandate at maximum.

[BR-67]-An Invoice shall contain maximum one Payment Mandate (BG-19)

count(cac:PaymentMeans/cac:PaymentMandate) <= 1
