### ISSUE TITLE
UBL: PaymentMeans & @schemeID checks

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#184]
- PaymentMeans/CardAccount/ PrimaryAccountNumber should have no attribute according to EN, however, no validation rule fires if @schemeID is present
- PaymentMeans/CardAccount/NetworkID: No rule fires if attribute @schemeID is present
- PaymentMeans/PaymentMandate/ID should have no attribute according to EN, however, no validation rule fires if @schemeID is present
- PaymentMeans/PaymentMandate/PayerFinancialAccount/ID should have no attribute according to EN, however, no validation rule fires if @schemeID is present

**Comment by oriol** [comment]
<assert test="$UBL-CR-674" flag="warning" id="UBL-CR-674">[UBL-CR-674]-A UBL invoice should not include the PrimaryAccountNumber schemeID</assert>
    <assert test="$UBL-CR-675" flag="warning" id="UBL-CR-675">[UBL-CR-675]-A UBL invoice should not include the NetworkID schemeID</assert>
    <assert test="$UBL-CR-676" flag="warning" id="UBL-CR-676">[UBL-CR-676]-A UBL invoice should not include the PaymentMandate/ID schemeID</assert>
    <assert test="$UBL-CR-677" flag="warning" id="UBL-CR-677">[UBL-CR-677]-A UBL invoice should not include the PayerFinancialAccount/ID schemeID</assert>
