### ISSUE TITLE
Relate license change to version

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#187]
Hi Oriol,
can you please add a note on the 1.3.0 release, that this was the first version released under the changed license.
Thanks,
  Philip

**Comment by oriol** [comment]
It is already stated in the README file

> License
> Licensed under European Union Public Licence (EUPL) version 1.2.
> 
> Derivative work created from https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/eInvoicing-EN16931-1.2.3
> 
> That was Licensed under the Apache License, Version 2.0

**Comment by phax** [comment]
Yes, but it would be good, if this would be explicitly stated as part of the 1.3.0 release - in a couple of releases it will be hard to deduce this.

**Comment by oriol** [comment]
Done
