### ISSUE TITLE
UBLVersionID

### ISSUE THREAD

**Issue by tjeb** [ConnectingEurope/eInvoicing-EN16931#189]
Currently, the rules specify that a document should not contain the UBLVersionID field.

This can cause several practical problems in processing documents; for starters, software may consider it 2.0 by default, or have put in elements from later versions than 2.1. Additionally, and potentially worse, software that generates SBDH envelopes now needs to have an external source of information to get to the full documentIdentifier value (as this includes the UBL version).

The workaround I see people put in place is to ignore the warning, and put it in anyway. IMHO this sets a bad precedent, and I would like to see this issue resolved.

The EN has no specific business rule for UBLVersionID, but it does only specify a mapping for UBL 2.1. So IMHO, the field should at the very least be allowed, and then have a rule that either warns or errors if the value is not 2.1 to conform to the current specification.

**Comment by MartinForsberg-Ecru** [comment]
I agree. Even though the syntax binding specifies 2.1 and the customizationid implicitly can be used, it would be better to communicate the minor version explicitly.
