### ISSUE TITLE
UBL rule: BR-CO-15 not correctly handling two TaxTotal elements

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#19]
The validation rule for BR-CO-15 does not handle the TaxCurrency and DocumentCurrency correctly. Now there is a check if the count of TaxTotal is >1, it uses TaxAmount where @currencyID = EUR. 

This will not allways be the case, the check should look for the value in DocumentCurrencyCode, and use the TaxTotal where @currencyID = DocumentCurrencyCode.

I added new unit test for this BR-CO-15-2

**Comment by oriol** [comment]
every $Currency in cbc:DocumentCurrencyCode satisfies cac:LegalMonetaryTotal/cbc:TaxInclusiveAmount = round( (cac:LegalMonetaryTotal/cbc:TaxExclusiveAmount + cac:TaxTotal/xs:decimal(cbc:TaxAmount[@currencyID=$Currency])) * 10 * 10) div 100

**Comment by oriol** [comment]
can you add the cbc:DocumentCurrencyCode in the unit tests?

**Comment by SiwMeckelborg** [comment]
Change done
