### ISSUE TITLE
An invoice object identifier cannot have attachment should be fatal

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#190]
The following issue was submitted to PEPPOL and the PEPPOL Devteam asks the TC434 Devteam to reconsider the severity (currently warning) and change to fatal.

"BT-18, Invoiced object identifier, and BG-24, Additional supporting documents, are completely separate business concepts in EN 16931-1: BT-18 is a reference to an object generating recurring (periodic) invoicing of consumption, linked to time or meter readings, while BG-24 represents specifications that substantiate the claims in an invoice. 

In the EN, BT-18 and BG-24 has no association to each other, but in the UBL binding both are mapped to AdditionalDocumentReference. Without restricting business rules, data combined with DocumentTypeCode="130" (representing BT18) and Attachment (representing BG-24) can be mixed in one and the same instance of AdditionalDocumentReference. In fact, we have already encountered one operator sending attached documents under the pretence of being invoiced objects, with the effect that receivers were unaware of the presence of the attachments in question.

This problem has been reported to, and processed by, TC 434 as issue #170. But in line with TC434 practice it resulted in a rule with severity “warning” only. In light of the high risk of losing data, and the fact that BT-18 and BG-24 are incompatible, I request a PEPPOL rule with severity “fatal”."

**Comment by oriol** [comment]
Make UBL-CR-666 fatal
