### ISSUE TITLE
Error in BR-S-03, assumes that CompanyID is VAT without checking (UBL)

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#192]
An invoice which has cac:PartyTaxScheme/cbc:CompanyID qualified with another TaxScheme than VAT, is still considered to be a VAT-number in BR-S-03.

Probably best to go through all references to VAT-number and make sure that [cac:TaxScheme/cbc:ID='VAT'] is used as qualifier.

https://docs.peppol.eu/poacc/billing/3.0/rules/BR-S-03/
Current rule, pointing to CompanyID without qualification.

(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'S'][cac:TaxScheme/normalize-space(upper-case(cbc:ID))='VAT']) and (exists(//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID) or exists(//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'VAT')]/cbc:CompanyID))) or not(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'S']))

**Comment by oriol** [comment]
Modify the xpath in BR-S-03 to:

(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'S'][cac:TaxScheme/normalize-space(upper-case(cbc:ID))='VAT']) and (exists(//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'VAT')]/cbc:CompanyID) or exists(//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/(normalize-space(upper-case(cbc:ID)) = 'VAT')]/cbc:CompanyID))) or not(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'S']))

Change it also in BR-S-04
