### ISSUE TITLE
UBL-CR-666 – Suggested editorial improvement

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#193]
The current error signal 
“[UBL-CR-666]-A UBL invoice should not include the AdditonalDocumentReference referring to an Invoice Object Identifier should not include an Attachment”
should be re-worded in order to increase clarity. 

Suggested new wording:
- Either “[UBL-CR-666]-A UBL invoice should not include an AdditonalDocumentReference simultaneously referring an Invoice Object Identifier and an Attachment”
- Or “[UBL-CR-666]-A UBL invoice with an AdditonalDocumentReference referring to an Invoice Object Identifier should not include also an Attachment”

**Comment by rkottmann** [comment]
I'd prefer a slight variant of your second option:

> [UBL-CR-666]-A UBL invoice with an AdditonalDocumentReference referring to an Invoice Object Identifier should not include an Attachment”

**Comment by oriol** [comment]
I think that they can include attachments, but not on the AdditionalDocumentReference that refers to an Invoice Object Identifier, so I would go for Soren's first option:

“[UBL-CR-666]-A UBL invoice should not include an AdditonalDocumentReference simultaneously referring an Invoice Object Identifier and an Attachment”
