### ISSUE TITLE
UBL: One more validation rule is needed for full BT-18 compliance 

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#194]
BT-18 (cardinality 0..1) includes an invoiced object identifier and possibly a scheme identifier, but no more.
In the current UBL binding it is possible to additionally include DocumentDescription without any validation rule signaling the excess information. Such a rule is needed.
(Note – this RFC is linked to #170 and #171, but slightly different from them)

**Comment by SLennartsson** [comment]
[Invoice_BT-18+DocumentDescription.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/3903165/Invoice_BT-18%2BDocumentDescription.txt)

**Comment by oriol** [comment]
Add rule [UBL-CR-673]-A UBL invoice should not include an AdditonalDocumentReference simultaneously referring an Invoice Object Identifier and an Document Description

With not(//cac:AdditionalDocumentReference[cbc:DocumentTypeCode  = '130']/cbc:DocumentDescription)
