### ISSUE TITLE
UBL (credit note only): More validation rules are needed for full BT-11 compliance

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#195]
BT-11 Project reference (cardinality 0…1) is bound to AdditionalDocumentReference for the UBL credit note. But AdditionalDocumentReference is also to cater for other business terms related to supporting documents which, unintentionally, has opened up for potential excess information when an instance of BT-11 is represented in the UBL credit note. One or more validation rules are needed to assure that BT-11 is represented by merely the following elements:
   <cac:AdditionalDocumentReference> 
         <cbc:ID>ABC123</cbc:ID>
         <cbc:DocumentTypeCode>50</cbc:DocumentTypeCode>
   </cac:AdditionalDocumentReference>

Notably, presence of DocumentDescription or Attachment in the same instance has to generate error signal.
[CreditNote_BT-11+ DocumentDescription+Attachment.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/3903157/CreditNote_BT-11%2B.DocumentDescription%2BAttachment.txt)

**Comment by oriol** [comment]
This requires a corrigenda in the EN syntax binding as it needs a qualifier to identify that this binding belongs to BT-11 and not to another BT.
