### ISSUE TITLE
UBL rule: BR-61 does not fire as expected

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#2]
BR-61 does not fire when Payment means code is 30 or 57, and PayeeFinancialAccount/ID is missing. See unit test BR-61

**Comment by oriol** [comment]
(exists(cac:PayeeFinancialAccount/cbc:ID) and ((cbc:PaymentMeansCode = '30') or (cbc:PaymentMeansCode = '57') ))  or ((cbc:PaymentMeansCode != '30') and (cbc:PaymentMeansCode != '57'))

**Comment by SiwMeckelborg** [comment]
BR-61 is still not firing correctly, and I cannot see that any change was done to this rule in the referenced commit. Please review rule and unit test file BR-61, test no 4 and 5 does not generate errors.
