### ISSUE TITLE
UBL rules: Wrong VAT category code for IPSI and IGIC VAT

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#20]
According to the latest UN/CEFACT 5305 codelist the correct VAT category codes should be 

L = Canary Island Tax 
M = Ceuta and Manilla Tax

http://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5305.htm

Please correct validation in all BR-IG and BR-IP rules to check for these two values.

**Comment by oriol** [comment]
Added rules with these new Codes

**Comment by oriol** [comment]
should I remove rules BR-CL-09 and BR-CL-10 ?

**Comment by SiwMeckelborg** [comment]
No, CL-09 and 10 are having code L and M as valid values.
