### ISSUE TITLE
BR-CL-08: BIS BILLING 3.0 rule is wrong for cbc:Note

### ISSUE THREAD

**Issue by senikk** [ConnectingEurope/eInvoicing-EN16931#200]
The rule for cbc:Note is wrong because it doesn't allow to use the character # twice in this free text field beause its looking for start and stop of # and not taking amount of chars between # should be 3 for these UNCL4451 codes.

From the rule at https://docs.peppol.eu/poacc/billing/3.0/rules/BR-CL-08/
`
substring-before(substring-after(.,'#'),'#')
`

Example from our customer not using these invoiced note subject codes at all but just marking a reference number like this with the # character.
`
<cbc:Note>Complaints #1234. Some more describtion. #1234. Some more text.</cbc:Note>
`

**Comment by wimkok** [comment]
This is also a problem when HTML character codes are used like &#09;

**Comment by klakegg** [comment]
Other points:
* The message says "SHOULD", and the flag says "fatal".
* BT-21 is bound to `/Invoice/cbc:Note`  and `/CreditNote/cbc:Note` as an optional element, however BT-22 is mandatory for the same element. This rule should trigger only when there are 2 note elements. Draft: `/ubl:Invoice/cbc:Note[../cbc:Note[2]][1]`
* The credit note context is `/cn:CreditNote/cac:Note`, however it should be "c**b**c:Note".

**Comment by oriol** [comment]
we will add a check for exact match of three characters between # 

(contains(.,'#') and string-length(substring-before(substring-after(.,'#'),'#'))=3 and ( ( contains(' AAA AAB AAC .. ZZZ ',substring-before(substring-after(.,'#'),'#') ) ) )) or not(contains(.,'#')) or not(string-length(substring-before(substring-after(.,'#'),'#'))=3)

Noted the shall and the typo in cac:Note.

Regarding the second comment from @klakegg : BT-21 and BT-22 are not bound to a second instance of the Note cbc. This would lead to a wrong usage of a text field in UBL. If BT-21 is not there in the first cbc:Note, there should be no problem, as it is optional. The mapping is concatenating these two BT into a single UBL data element.

**Comment by klakegg** [comment]
From the model mapping:

| ID | BT | Card. | Path |
| -- | -- | ---- | ---- |
| `BT-21` | Invoice note subject code | `0..1` | `/Invoice/cbc:Note` |
| `BT-22` | Invoice note | `1..1` | `/Invoice/cbc:Note` |

Both `BT-21` and `BT-22` is bound to the same path, and the mapping table from TC434 shows the cardinality of `cbc:Note` from UBL to be `0..n`.

Looking at the Italian CIUS is it clearly indicated a maximum length of `BT-21` and `BT-22` combined. Both of us know what is stated by UBL in this case, however it doesn't seem like the rules in UBL is followed for this text element.

PEPPOL BIS Billing 3.0 has restricted BT-21 to `0..0`, thus should rules related to `BT-21` not trigger for instance documents of that CIUS.

Based on this is my proposal to still implement the rules of `BT-21` to trigger only in the situation where there are two `cbc:Note` elements.

**Comment by oriol** [comment]
It is the same path, meaning the same data element, and there is a note in BT-21  stating its usage as "Use #subject code#". I think that should not be confused with having two different repetitions of the cbc:Note element to support these two BT's. Maybe there is a need for a corrigenda better explaining how to support this business term.

The Italian CIUS is something different and we cannot assess on its validity here. But in case the Italian CIUS is not following the UBL rules, they should correct their CIUS, of course.

So I think we shall not allow for two cbc:Note elements unless they are used for translation purposes, as required in UBL.
