### ISSUE TITLE
Change in rule BR-17

### ISSUE THREAD

**Issue by OGlanzmann** [ConnectingEurope/eInvoicing-EN16931#201]
Forwarded from PEPPOL jira issue POACC-290:

"We stubbled upon a oddness in the rule BR-17 
https://docs.peppol.eu/poacc/billing/3.0/rules/BR-17/

In the test part it states: 
```xpath
exists(cac:PartyName/cbc:Name) 
and (not(cac:PartyName/cbc:Name = ../cac:AccountingSupplierParty/cac:Party/cac:PartyName/cbc:Name) 
and not(cac:PartyIdentification/cbc:ID = ../cac:AccountingSupplierParty/cac:Party/cac:PartyIdentification/cbc:ID) 
and not(cac:PartyLegalEntity/cbc:RegistrationName = ../cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationName))
```

The last AND of the rule is the question, why is it there when Invoice/PayeeParty/PartyLegalEntity does not have the element RegistrationName in the spec?

https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-PayeeParty/cac-PartyLegalEntity/

Implementers using the rules as structural guidance may by mistake put in the RegistrationName element because it is stated in the rule although it is not stated in the actual specification.

Is this part of the rule in the validation by design or by oversight?
Should the last and of the rule be removed?"

**Comment by oriol** [comment]
Agree to remove the last and of the rule. Will be:

exists(cac:PartyName/cbc:Name) and (not(cac:PartyName/cbc:Name = ../cac:AccountingSupplierParty/cac:Party/cac:PartyName/cbc:Name) and not(cac:PartyIdentification/cbc:ID = ../cac:AccountingSupplierParty/cac:Party/cac:PartyIdentification/cbc:ID) )
