### ISSUE TITLE
BIS 3 Credit note validation rule

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#202]
The validation rule https://docs.peppol.eu/poacc/billing/3.0/rules/BR-E-09/ for BIS 3 Credit Note causes a CRITICAL validation error when the value equals -0.00.

If anything, we believe a WARNING would be more fair if this rule remains and it would be good to throw an error that informs the user about the details to why the error was triggered.
Issue originally reported to Peppol as https://openpeppol.atlassian.net/browse/PEPPOL-2271

**Comment by MartinForsberg-Ecru** [comment]
To my understanding, there is no problem with the rule itself ("../cbc:TaxAmount = 0") but it seems some implementations of schematron incorrectly consider -0 to not equal 0. I think those implementations should be corrected rather than modifying the rule.

/Martin
