### ISSUE TITLE
Sales order reference is dependent on order reference existing

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#203]
The following was reported to Peppol as issue https://openpeppol.atlassian.net/browse/PEPPOL-2281
---
BT-13, Purchase order reference, and BT-14, Sales order reference, both have cardinality 0..1 in EN 16931-1, and the two business terms can be used independently of each other.

In BIS Billing 3, with UBL syntax representation, this translates into
0..1 • cac:OrderReference
1..1 • • cbc:ID Purchase order reference
0..1 • • cbc:SalesOrderID
which means that sales order reference can be used only when a purchase order reference exists In BIS Billing 3. We have suppliers in Sweden who wish to state sate sales order reference irrespective of any purchase order being known.

Issue 1: I cannot spot it as a documented restriction in Appendix A of the BIS.
Issue 2: If the restriction is inherit in UBL not much can be done, but otherwise the restriction should be removed.
---
This is due to the UBL syntax cardinality that if cac:OrderReference is used then it must contain a cbc:ID which is what the Purchased order reference is mapped to. Nevertheless, the syntax representation should implement the semantic data model as defined so a workaround should be investigated.

**Comment by oriol** [comment]
Unfortunately, this is an inheritance from UBL, where the cbc:ID is mandatory as per the UBL Schema. 

The easiest workaround would be to use a "fake" OrderID such as a "dash" to support the requirement of mandatory use when this element does not actually exist in the document instance.

A second potential workaround could be:
- Using cbc:ID with an schemeID qualifying the identifier to OrderID or cbc:SalesOrderID.
- When both elements present, use the mapping as it is now (with the schemeID pointing to OrderID)

But this would lead to extra controls, such as having multiple SalesOrderID, and I see it more difficult to implement.
