### ISSUE TITLE
Update codes according to latest listing of codes

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#204]
The attached spreadsheet contains all the code lists that are used in the EN. The validation artefacts need to be updated accordingly. Please refer to the Index tab for an overview of all codes and which of them have changed.

There has been discrepancy in the codes so it might be good to compare all the code values in the EN validation with the codes in the spreadsheet. This is the listing that is published on the CEF site as normative.

**Comment by midran** [comment]
[EN16931 code lists values used from 2020-02-14.xlsx](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/4205288/EN16931.code.lists.values.used.from.2020-02-14.xlsx)

**Comment by rkottmann** [comment]
Hi, is this closed, because it was updated or rejected?

**Comment by oriol** [comment]
Code lists have been updated.
