### ISSUE TITLE
Use of due dates in CreditNotes

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#206]
Rule UBL-CR-412 may be preventing the use of Due Date in Credit Notes. Issue #84 was concerned with not forcing the use of due date in Credit Notes but there seem to be some who want to use the due date. This issue is filed based on issues https://openpeppol.atlassian.net/browse/POACC-313 in Peppol and https://openpeppol.atlassian.net/browse/POACC-305
When rule 412 is modified to allow the use of due date in Credit Note, then since the payment mean class may appear unbounded. The EN however restricts that due date may only appear once. Therefore there may be a need for a rule that restricts the due date to only appear once or always be the same. This concern is raised in Peppol issues https://openpeppol.atlassian.net/browse/POACC-308 and https://openpeppol.atlassian.net/browse/POACC-309

**Comment by oriol** [comment]
the quickest fix would be to remove this rule. Is this acceptable?

**Comment by oriol** [comment]
Instead of removing the rule, just check that the root element is not cn:CreditNote would suffice
