### ISSUE TITLE
Stylesheet file for CrossIndustryInvoice  format

### ISSUE THREAD

**Issue by arditkazazi** [ConnectingEurope/eInvoicing-EN16931#208]
Hello, 
does it exists any stylesheet file for CII invoices like it exists for UBL files? 
If yes where can I download it? 

Regards,
Ardit

**Comment by MartinForsberg-Ecru** [comment]
Hi, SFTI (Single Face To Industry, Sweden) has developed and published a tranformation stylesheet which converts CII to UBL. Not ideal perhaps, but you could use a two-step transformation from CII->UBL->Presentation.

The transformation stylesheet assumes that the CII-instance is valid and compliant to the Peppo BIS CIUS. 


https://github.com/SingleFaceToIndustry/SFTI-repository/tree/master/PEPPOL%20BIS%20Billing%203/CII-To-UBL%20Transformation/XSLT

There is a also a multi-lingual (currently Swedish, English and Polish) presentation stylesheet published by SFTI: https://github.com/SingleFaceToIndustry/SFTI-repository/blob/master/PEPPOL%20BIS%20Billing%203/Presentation%20Stylesheet/Stylesheet_BIS-BILLING-3_Invoice%2BCreditNote.zip
