### ISSUE TITLE
Cardinality conflict for BT-60 and BT-90

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#209]
Following issue reported to Peppol in https://openpeppol.atlassian.net/browse/POACC-260
In the EN 16931 data model BT-60 and BT-90 are business terms that are defined independently of each other:

- BT-60 Payee identifier with cardinality 0..1, is used in the seller-buyer relation as a general identifier of the payee.
- 
- BT-90 Bank assigned creditor identifier (cardinality 0..1) is used in case of SEPA direct debit; depending on the applicable payment arrangement BT-90 is associated to either the seller or to a payee. 

In the case a Payee is involved: in PEPPOL BIS Billing 3 with UBL syntax binding, BT-60 and BT-90 both map onto PayeeParty/PartyIdentification/ID. However, the cardinalities stated in the syntax block simultaneous use of the BT-60 and BT-90 identifiers. This situation might arise if the payment provision is to be based on factored SEPA direct debit. 

We have not yet seen any problem in Sweden with the current solution. But the restriction should be documented, and guidance should be given on how to handle a conflict of terms.

**Comment by oriol** [comment]
There is no current rule in the validation artefacts blocking the possibility to have both BT-60 and BT-90.

**Comment by phax** [comment]
See also #92, #104 and #126
