### ISSUE TITLE
cac:PaymentMeans/cac:PayerFinancialAccount should not be valid

### ISSUE THREAD

**Issue by senikk** [ConnectingEurope/eInvoicing-EN16931#215]
https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-PaymentMeans/

One of our customers received a BIS BILLING 3.0 invoice with cac:PaymentMeans/cac:PayerFinancialAccount which unfortunately validated 100% ok. 

Following the BIS BILLING 3.0 docs it should have been cac:PaymentMeans/cac:PayeeFinancialAccount, the cac:PayerFinancialAccount with Payer instead of Payee is only available for cac:PaymentMeans/cac:PaymentMandate and not inside cac:PaymentMeans

**Comment by oriol** [comment]
Add a new syntax rule to avoid the use of cac:PaymentMeans/cac:PayerFinancialAccount
