### ISSUE TITLE
Code list validation for cac:DeliveryLocation/ID

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#217]
The en states that when used the schemeID for delivery location ID shall be from the ICD code list. There does not seem to be a validation rule checking that.

This was forwarded from Peppol Issue PEPPOL-2691

**Comment by oriol** [comment]
Add a rule checking whether cac:DeliveryLocation/cbc:ID@schemeID is coded according to ISO 6523.
