### ISSUE TITLE
Weird characters at the end of rule "BR-E-05"

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#220]
Hi,
the error message of `BR-E-05` has trailing characters that should b removed, because they lead to different behaviour on Windows and Linux:
![grafik](https://user-images.githubusercontent.com/196219/85606299-50a8c500-b653-11ea-886e-b78514b37dba.png)

Please check other rule texts also for the occurrance of "C2" and "A0" (hex) characters.

Thanks, Philip

**Comment by wimkok** [comment]
Character sequence occures several times. We are getting Decoder errors because of this.

**Comment by phax** [comment]
It should be very easy to fix...
