### ISSUE TITLE
No error if providing multiple Buyer VAT numbers

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#228]
Report initially submitted to Peppol helpdesk. Forwarded here as we think the rule belongs in the EN validation artefacts.

The EN allows for only one repetition of the Buyer VAT number. In the UBL syntax, this element is mapped to cac:PartyTaxScheme/cbc:CompanyID. 

**The issue**: the cac:PartyTaxScheme is unbounded in UBL and there is no syntax-rule which ensures that only one repetition is used. 

**Proposal**: add a cardinality rule on cac:PartyTaxScheme (under cac:AccountingCustomerParty) limiting it to 0..1

/Martin

**Comment by oriol** [comment]
Continue in #230

**Comment by MartinForsberg-Ecru** [comment]
I would like to request to reopen this very old issue since the same problem was just reported to Peppol. 

It seems that this issue was closed and continued in issue #230. However, the 230-issue was about Supplier Party Tax Scheme, not the Buyer Party Tax Scheme.

So the problem remains - the Buyer cac:PartyTaxScheme is unbounded in UBL and there is no syntax-rule which ensures that only one repetition is used.

Proposal: add a cardinality rule on cac:PartyTaxScheme (under cac:AccountingCustomerParty) limiting it to 0..1

**Comment by oriol** [comment]
@MartinForsberg-Ecru, isn't [UBL-SR-18]-Buyer VAT identifier shall occur maximum once not enough?
