### ISSUE TITLE
UBL-SR-47 should have severity “fatal” 

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#231]
Ref: UBL-SR-47 “When there are more than one payment means code, they shall be equal”
Issue: EN16931-1 is very clear, just one payment means code is allowed (cardinality 0..1). 
So, there is no reason why deviations merely should be warned when the UBL syntax is being used.
Suggestion: Change the rule to fatal; we have already come across several instances of inadequate implementation.

**Comment by ConnectingEurope** [comment]
Originates from Peppol https://openpeppol.atlassian.net/browse/POACC-307

**Comment by oriol** [comment]
see #214
