### ISSUE TITLE
Assessing the wider implications of the August 2019 hotfix

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#233]
Issue: The EN 16931-1 seem to regard negative invoice and credit note as equal alternatives (see, for example, business process P1or P9). This, in turn, would imply that positive invoice and negative credit note may be seen as equals as well. 
Through the August 2019 hotfix a first step was taken away from the symmetric (mirrored) function of negative invoice and credit note, in that BR-CO-25 no more implemented in a way that is reflecting the wording of EN16931-1. This change was introduced in consequence if technical issues related to rule BR-CO-25 itself but without any documentation of its high-level implications on invoice – credit note functionalities.
Request: 
a) Peppol need to articulate its position on the how invoice and credit note may (and may not) relate, to be in line with EN 16931-1 or to deviate.
b) Whatever position Peppol arrives at under step a): Concluding on a fundamental principle in invoicing, Peppol would have do document its position in visible way (and note hide it in a release note to a technical validation rule). Tentatively any deviation from EN 16931-1 (if so decided) would involve review of section 4.6 and Appendix A of https://docs.peppol.eu/poacc/billing/3.0/bis/ 

Originates from Peppol https://openpeppol.atlassian.net/browse/POACC-304

**Comment by oriol** [comment]
See #232
