### ISSUE TITLE
SCH file version

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#234]
Just downloaded the CEN SCH file from http://docs.peppol.eu/poacc/billing/3.0/files/CEN-EN16931-UBL.sch

At some point, someone will end up with 2 (or more) copies of this file... and which one is the the newest??

Please add a version number and release date into the files!
Resolution

Reopened and changed to a Rfc instead of a Bug

Originates from Peppol https://openpeppol.atlassian.net/browse/POACC-153

See related discussion below.

**Comment by ConnectingEurope** [comment]
Georg Birgisson
May 16, 2019, 10:12 AM

Hi,

It turned out be not as simple as it sounds because the .sch files are autogenerated, requiring changes to the scripts and there we had some resource issues. This, and other things, has prompted plans to change the organization of the development but that will not be effective until the next release. Sorry about this.

Regards,

Georg

From: Peter Sone Koldkjær (Jira) <jira@openpeppol.atlassian.net> 
Sent: fimmtudagur, 16. maí 2019 09:00
To: georg@midran.com
Subject: [JIRA] (POACC-153) SCH file version

<https://avatar-cdn.atlassian.com/1341e8e795c861f784ec7a85e399502f?s=48&d=https%3A%2F%2Fopenpeppol.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dpsk%26avatarId%3D10440%26noRedirect%3Dtrue> 

<https://openpeppol.atlassian.net/secure/ViewProfile.jspa?accountId=557058%3A02bc911f-fea4-4471-a2fb-b2349f6896da> Peter Sone Koldkjær commented on  <https://openpeppol.atlassian.net/browse/POACC-153?atlOrigin=eyJpIjoiNDJlMmRlZjQzZGUzNGNiYThkZjJkMmJmZjZmMDMwODkiLCJwIjoiaiJ9> 

POACC-153: SCH file versionIn Progress 

<https://openpeppol.atlassian.net/browse/POACC-153?atlOrigin=eyJpIjoiNDJlMmRlZjQzZGUzNGNiYThkZjJkMmJmZjZmMDMwODkiLCJwIjoiaiJ9> Re: SCH file version 

Just looked at the released SCH files - and cannot find any kind of version information in these (mandatory date, version number, etc.)

<https://openpeppol.atlassian.net/browse/POACC-153#add-comment?atlOrigin=eyJpIjoiNDJlMmRlZjQzZGUzNGNiYThkZjJkMmJmZjZmMDMwODkiLCJwIjoiaiJ9> 

<https://openpeppol.atlassian.net/browse/POACC-153#add-comment?atlOrigin=eyJpIjoiNDJlMmRlZjQzZGUzNGNiYThkZjJkMmJmZjZmMDMwODkiLCJwIjoiaiJ9> Add Comment 

Get Jira notifications on your phone! Download the Jira Cloud app for  <https://play.google.com/store/apps/details?id=com.atlassian.android.jira.core&referrer=utm_source%3DNotificationLink%26utm_medium%3DEmail> Android or  <https://itunes.apple.com/app/apple-store/id1006972087?pt=696495&ct=EmailNotificationLink&mt=8> iOS 
Oscar Glanzmann
November 1, 2019, 10:38 AM

Closed, the issue of release numbering is beeing adressed in the more general project of revision work. No need to keep it as a separate topic.
Former user
November 11, 2019, 8:37 AM

Still an issue - not fixed in fall release 2019.
Georg Birgisson
November 12, 2019, 4:35 PM

It is still an issue. We are restructuring our release and development processes and the fall release was the last release going through the old process. Adding release numbers will be part of the changes we are making in the next release for the spring.
Former user
November 13, 2019, 7:09 AM

👍
Georg Birgisson
now

Forwarded to TC434 (CEF) as 

https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/234 - Connect to preview Closed as peppol issue.

**Comment by phax** [comment]
What about giving the build scripts an additional parameter "version" that you pass when building the Schemtraons. That should be minimal invasive and would really help. Just adding an XML comment `<!-- Schematron Version $version -->` would suffice I guess...

**Comment by phax** [comment]
This one didn't made it in 1.3.5 :/
