### ISSUE TITLE
Replace `.` with `@unitCode`

### ISSUE THREAD

**Issue by christian-schlichtherle** [ConnectingEurope/eInvoicing-EN16931#238]
This line does not match the `unitCode` attribute:

https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/34282127d0470ff897506c1d5d13e05fba46d7ed/cii/schematron/codelist/EN16931-CII-codes.sch#L150

Same here:

https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/34282127d0470ff897506c1d5d13e05fba46d7ed/cii/schematron/preprocessed/EN16931-CII-validation-preprocessed.sch#L986

And here:

https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/34282127d0470ff897506c1d5d13e05fba46d7ed/cii/schematron/preprocessed/EN16931-CII-validation-preprocessed.sch#L989

**Comment by oriol** [comment]
the match is in the context.

**Comment by christian-schlichtherle** [comment]
I've seen that, but it doesn't work. You can put in whatever you want and the business rule will not trigger. That's because in XSLT you cannot have an attribute as a context, AFAIK.

**Comment by oriol** [comment]
Was checking the sch. Will have another look. Thanks for checking!

**Comment by christian-schlichtherle** [comment]
... therefore, the same business rule is expressed slightly different for UBL, and there it works.
