### ISSUE TITLE
UBL-CR-666 - description does not match flag

### ISSUE THREAD

**Issue by Gdekerpel** [ConnectingEurope/eInvoicing-EN16931#239]
The text for UBL-CR-666 reads "_A UBL invoice **should not** include an AdditonalDocumentReference simultaneously referring an Invoice Object Identifier and an Attachment_" but it is flagged as a `FATAL` error.

Should this not become a `WARNING` therefor?

**Comment by oriol** [comment]
This comes from a change in v1.3.1. requested by Peppol here: #90 
The problem is that the wording of the business rule was not correctly changed.
Will change _should_ to _shall_ in the assertion.
