### ISSUE TITLE
ISO 20022 instance files does not comply to XSD

### ISSUE THREAD

**Issue by klakegg** [ConnectingEurope/eInvoicing-EN16931#24]
Instance files created for ISO 20022 does not comply to scheme as there is something wrong in the instance files. This should be fixed.

**Comment by phax** [comment]
~Did you take the `XML Schemas 16B (SCRDM - CII)` schemas from http://www.unece.org/cefact/xml_schemas/index.html ??~

**Comment by klakegg** [comment]
Why would I take the ISO 20022 schemas from UN/ECE?

**Comment by phax** [comment]
Mea culpa - forget it. My mistake :(

**Comment by phax** [comment]
As discussed in todays CEN WG6 meeting, the support for ISO 20022 is discontinued meaning we wont look into this issue
