### ISSUE TITLE
Should it be NOR or OR in the text for BR-Z-10

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#240]
[BR-Z-10]-A VAT breakdown (BG-23) with VAT Category code (BT-118) "Zero rated" shall not have a VAT exemption reason code (BT-121) or VAT exemption reason text (BT-120).

Shouldn't it be ... (BT-121) nor VAT exemption reason text (BT-120).

Issue originates from issue PEPPOL-3263

**Comment by oriol** [comment]
The wording is from the EN 16931-1
