### ISSUE TITLE
Incorrect Context for rule BR-CO-25

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#241]
https://docs.peppol.eu/poacc/billing/3.0/rules/BR-CO-25/
The context says only invoice /ubl:Invoice/cac:LegalMonetaryTotal/cbc:PayableAmount

But usage says both Invoice and Credits. 

I guess this also messes with UBL-SR-45?

Originates from issue PEPPOL-3259

**Comment by oriol** [comment]
As discussed here #84 this rule should only be applied to invoices, not to credit notes.
