### ISSUE TITLE
BR-CO-16 triggered on UBL for 1.3.3

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#242]
Hi guys,
since the latest 1.3.3 update, the following UBL block is invalid:
```xml
 <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="EUR">10781.25</cbc:LineExtensionAmount>
      <cbc:TaxExclusiveAmount currencyID="EUR">10781.25</cbc:TaxExclusiveAmount>
      <cbc:TaxInclusiveAmount currencyID="EUR">12829.69</cbc:TaxInclusiveAmount>
      <cbc:AllowanceTotalAmount currencyID="EUR">0</cbc:AllowanceTotalAmount>
      <cbc:ChargeTotalAmount currencyID="EUR">0</cbc:ChargeTotalAmount>
      <cbc:PrepaidAmount currencyID="EUR">12829.69</cbc:PrepaidAmount>
      <cbc:PayableRoundingAmount currencyID="EUR">0</cbc:PayableRoundingAmount>
      <cbc:PayableAmount currencyID="EUR">0</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
```
I think the calculation model would now require `TaxInclusiveAmount` to be 0???
```
[BR-CO-16]-Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Paid amount (BT-113) +Rounding amount (BT-114).]]; 

(exists(cbc:PrepaidAmount) and not(exists(cbc:PayableRoundingAmount)) and (xs:decimal(cbc:PayableAmount) = (round((xs:decimal(cbc:TaxInclusiveAmount) - xs:decimal(cbc:PrepaidAmount)) * 10 * 10) div 100))) or (not(xs:decimal(cbc:PrepaidAmount)) and not(xs:decimal(cbc:PayableRoundingAmount)) and xs:decimal(cbc:PayableAmount) = xs:decimal(cbc:TaxInclusiveAmount)) or (xs:decimal(cbc:PrepaidAmount) and xs:decimal(cbc:PayableRoundingAmount) and ((round((xs:decimal(cbc:PayableAmount) - xs:decimal(cbc:PayableRoundingAmount)) * 10 * 10) div 100) = (round((xs:decimal(cbc:TaxInclusiveAmount) - xs:decimal(cbc:PrepaidAmount)) * 10 * 10) div 100))) or (not(xs:decimal(cbc:PrepaidAmount)) and xs:decimal(cbc:PayableRoundingAmount) and ((round((xs:decimal(cbc:PayableAmount) - xs:decimal(cbc:PayableRoundingAmount)) * 10 * 10) div 100) = xs:decimal(cbc:TaxInclusiveAmount)))
```

**Comment by oriol** [comment]
No, the problem is the expression. Should be

(exists(cbc:PrepaidAmount) and not(exists(cbc:PayableRoundingAmount)) and (xs:decimal(cbc:PayableAmount) = (round((xs:decimal(cbc:TaxInclusiveAmount) - xs:decimal(cbc:PrepaidAmount)) * 10 * 10) div 100))) or (not(exists(xs:decimal(cbc:PrepaidAmount))) and not(exists(xs:decimal(cbc:PayableRoundingAmount))) and xs:decimal(cbc:PayableAmount) = xs:decimal(cbc:TaxInclusiveAmount)) or (exists(xs:decimal(cbc:PrepaidAmount)) and exists(xs:decimal(cbc:PayableRoundingAmount)) and ((round((xs:decimal(cbc:PayableAmount) - xs:decimal(cbc:PayableRoundingAmount)) * 10 * 10) div 100) = (round((xs:decimal(cbc:TaxInclusiveAmount) - xs:decimal(cbc:PrepaidAmount)) * 10 * 10) div 100))) or (not(exists(xs:decimal(cbc:PrepaidAmount))) and exists(xs:decimal(cbc:PayableRoundingAmount)) and ((round((xs:decimal(cbc:PayableAmount) - xs:decimal(cbc:PayableRoundingAmount)) * 10 * 10) div 100) = xs:decimal(cbc:TaxInclusiveAmount)))

**Comment by phax** [comment]
Okay thanks. Meaning there will be a 1.3.4 release soon?

**Comment by oriol** [comment]
spring 2021 release

**Comment by phax** [comment]
Ah okay. That renders the 1.3.3 release quite useless if such a showstopper bug is in it. Can you eventually consider releasing a 1.3.3.1 bugfix release?

**Comment by oriol** [comment]
This is an old bug. The error has not been noticed because it only appears when there is a PayableRoundingAmount with value 0. 

I would then suggest waiting to the next release to fix the bug.

**Comment by phax** [comment]
The issue poped up when converting CII documents to UBL and that was not changed.
The output validated with 1.3.2 validation artefacts but fails with 1.3.3 - so something in this regard was changed.

**Comment by phax** [comment]
The problem was caused by commit https://github.com/ConnectingEurope/eInvoicing-EN16931/commit/d925641ab610079574dfad6425d54de1591ac40f which was meant to resolve #222

**Comment by phax** [comment]
I guess your proposal can be simplified to:
```js
(exists(cbc:PrepaidAmount) and not(exists(cbc:PayableRoundingAmount)) and (xs:decimal(cbc:PayableAmount) = (round((xs:decimal(cbc:TaxInclusiveAmount) - xs:decimal(cbc:PrepaidAmount)) * 10 * 10) div 100))) or 
(not(exists(cbc:PrepaidAmount)) and not(exists(cbc:PayableRoundingAmount)) and xs:decimal(cbc:PayableAmount) = xs:decimal(cbc:TaxInclusiveAmount)) or 
(exists(cbc:PrepaidAmount) and exists(cbc:PayableRoundingAmount) and ((round((xs:decimal(cbc:PayableAmount) - xs:decimal(cbc:PayableRoundingAmount)) * 10 * 10) div 100) = (round((xs:decimal(cbc:TaxInclusiveAmount) - xs:decimal(cbc:PrepaidAmount)) * 10 * 10) div 100))) or 
(not(exists(cbc:PrepaidAmount)) and exists(cbc:PayableRoundingAmount) and ((round((xs:decimal(cbc:PayableAmount) - xs:decimal(cbc:PayableRoundingAmount)) * 10 * 10) div 100) = xs:decimal(cbc:TaxInclusiveAmount)))
```

**Comment by phax** [comment]
Not emitting `PayableRoundingAmount` if the value is `0` is a suitable work around

**Comment by oriol** [comment]
Ok @phax, I have added a test on this and will fix it for the next release.

**Comment by juskoljo** [comment]
Should this introduced bug be communicated somehow? At least mentioned in "News and noteworthy" section ✌️

**Comment by oriol** [comment]
> Should this introduced bug be communicated somehow? At least mentioned in "News and noteworthy" section ✌️

Added a Note in the Release explaining the error.

**Comment by senikk** [comment]
@oriol where is this note added? Can't see it commited to README.

**Comment by phax** [comment]
It is referenced at https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.3
