### ISSUE TITLE
Incorrect XPath for BR-Z-08 in CII

### ISSUE THREAD

**Issue by rkottmann** [ConnectingEurope/eInvoicing-EN16931#246]
One of our users reports a side effect BR-Z-08 using the Raptor Engine instead of Saxon the of https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/39

I assume that (but did not check) that
```xml
 /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator=true() and ram:CategoryTradeTax/ram:CategoryCode='Z']/ram:ActualAmount
```
might be changed to (just scribbling)
```xml
 /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ cast as xs:boolean ram:ChargeIndicator/udt:Indicator  =true() and ram:CategoryTradeTax/ram:CategoryCode='Z']/ram:ActualAmount
```

or something like that.

**Comment by svanteschubert** [comment]
> ```
> udt:Indicator=true()
> ```

I had a similar XPatch Exception with Saxon 12.4, the problem can be solved by changing 
```
udt:Indicator=true()
```
to
``` 
udt:Indicator='true'
```
see also https://www.ibm.com/support/pages/xpath-differences-exist-when-comparing-boolean-values-business-object-bo-lazy-parsing-and-business-object-eager-parsing-mode
