### ISSUE TITLE
Missing Codes in BR-CL-23

### ISSUE THREAD

**Issue by EskerEDIServices** [ConnectingEurope/eInvoicing-EN16931#247]
During the XRechnung tests we noticed an inconsistency in the EN16931 validation:
 
The rule states that UnitCodes must comply with UNECERec20 with extension by UNECERec21.
If I now check the unit code "RO" in https://docs.peppol.eu/poacc/billing/3.0/codelist/UNECERec21/, it is allowed.
However, in the documentation of this rule (https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-tc434/BR-CL-23/), as well as in the validation stylesheet "EN16931-UBL-validation.xsl" the code is not included.
 
Is this inconsistency already known? Is there a reason why not all codes from UNECERec21 have been included in the rule?

**Comment by SLennartsson** [comment]
We (SFTI) have RO - roll - in our shortlist of UoM, implemented as XRO. 
It works - please note the implementation rule in section 10.11 of
https://docs.peppol.eu/poacc/billing/3.0/bis/

**Comment by oriol** [comment]
@midran can you look at this issue. The code RO is not in the current code list identified in #271

**Comment by oriol** [comment]
You need to use XRO. 

The codes from Rec 21 shall be prefixed with an X and this code is on the list. This is in accordance with the rules defined by ISO when using Rec 20 and Rec 21 together.
