### ISSUE TITLE
Problems with validating UBL-SR-06

### ISSUE THREAD

**Issue by lasjan** [ConnectingEurope/eInvoicing-EN16931#248]
There seems to be at least two problems with rule UBL-SR-06.

1. Provided Context is incorrect. cac:InvoiceDocumentReference does not exist in cac:Invoice nor in cac:CreditNote. 
2. This rule stands in contradiction with EN16931, which clearly allows having multiple preceeding invoice references.

**Comment by SLennartsson** [comment]
You seem to have missed out the fact that cac:BillingReference forms part of the context for cac:InvoiceDocumentReference.

In EN16931-1:
- Business group BG-3, Preceding invoice reference, may repeat 
- Business term BT-25, Preceding invoice reference (part of BG-3), has cardinality 1..1 

In UBL: 
- BG-3 is bound to cac:BillingReference (it may repeat)
- BT-25 is bound to cac:BillingReference/cac:InvoiceDocumentReference/cbc:ID which has exakt one occurrence within a cac:BillingReference

**Comment by oriol** [comment]
The comment from @SLennartsson clarifies there is no issue.
