### ISSUE TITLE
Norwegian invoices with both debit transfer (31) and giro payment (50, 56)

### ISSUE THREAD

**Issue by juskoljo** [ConnectingEurope/eInvoicing-EN16931#249]
Hi!

`[UBL-SR-47]-When there are more than one payment means code, they shall be equal`

As UBL-SR-47 severity changed from warning to fatal in 2020 fall release is it really so that you cannot have these payment instructions at the same time? If that is the case, why not?

Thanks in advance!

With best regards,
Jussi

**Comment by SLennartsson** [comment]
Refer to the data model in EN 16931-1:
- Business group BG-16, Payment instruktions, has cardinality 0..1
- Business term BT-81, Payment means type code, (being a component of BG-16 has cardinality 1..1.

If you are interested, the fix we have in Sweden is documented on https://sfti.se/standarder/peppolbisochsvehandel/peppolbisbilling3/implementationsradochfaq.4728.html (but I am not sure it will work for you).

**Comment by oriol** [comment]
Explained by @SLennartsson.
