### ISSUE TITLE
Missing UoM code NM3 in schematron

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#250]
The UoM-code NM3 is listed in the Rec20 Codelist but not included in the schematron BR-CL-23.

https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931#RegistryofsupportingartefactstoimplementEN16931-Codelists

For next release I propose that the a comparison of the BR-CL-23 listed values is done towards the published codelist.

**Comment by oriol** [comment]
will be added as per #271
