### ISSUE TITLE
Validation Error BR-S-08 XRechnung 

### ISSUE THREAD

**Issue by rhedrich** [ConnectingEurope/eInvoicing-EN16931#253]
Hey there, always getting the error:
[BR-S-08]-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "Standard rated", the VAT category taxable amount (BT-116) in a VAT breakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "Standard rated" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).
For every xRechnung 1.2 and xRechnung 2.0 that i created.
Although the price amounts etc. are perfectly matching.
Same invoice, same values etc. is validating fine with the zugferd profiles.
This only happens when validating xRechnung, here with the validator or any other validator on the net.
Maybe someone could give me and hand, and check the invoice and give me a little hint why that is?
Can i get any help on this from anyone?

**Comment by phax** [comment]
Are you using sub-invoice lines?

**Comment by rhedrich** [comment]
Any way to get in direct contact, so i could send someone the invoice?

**Comment by phax** [comment]
.... but I don't really have much capacity for support :/

**Comment by oriol** [comment]
Hi @rhedrich, can you send me the examples as well? oriol@invinet.org

**Comment by rkottmann** [comment]
And if it has subinvoicelines as well to us xr...@finanzen.bremen.de

**Comment by oriol** [comment]
@rhedrich, have you resolved the issue? Can you send some examples?

**Comment by oriol** [comment]
It is not possible to assess without any example. Please reopen if an example is available.

**Comment by phax** [comment]
Eventually similar to https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/74 ???
