### ISSUE TITLE
validation error in BR-CO-17 - still "round"-Problems with negative invoices

### ISSUE THREAD

**Issue by OnlyDex** [ConnectingEurope/eInvoicing-EN16931#256]
In relation to issue #119, it seems to me that the fix for the CII wasn´t completly correct (only BR-S-9 works). I get still validation errors in case of negative invoices. In UBL, however is everything fine (#120).

In comparison to the BR-S-9, it is noticeable that the in BR-CO-17 lacks the abs und decimal-cast function.

**Comment by phax** [comment]
In general: the UBL version of BR-CO-17 has a slack of 1, whereas the CII version doesn't have a slack (up to and including 1.3.4). Is that by purpose?

**Comment by phax** [comment]
This is related to #303
