### ISSUE TITLE
Ruleset 1.3.3 - UBL - BR-CO-15 is broken if more than one TaxAmount is present

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#257]
A UBL CreditNote having 2 TaxTotal sections
```xml
  <cac:TaxTotal>
      <cbc:TaxAmount currencyID="EUR">2048.44</cbc:TaxAmount>
      <cac:TaxSubtotal>
         <cbc:TaxableAmount currencyID="EUR">10781.25</cbc:TaxableAmount>
         <cbc:TaxAmount currencyID="EUR">2048.44</cbc:TaxAmount>
         <cac:TaxCategory>
            <cbc:ID>S</cbc:ID>
            <cbc:Percent>19</cbc:Percent>
            <cac:TaxScheme>
               <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
         </cac:TaxCategory>
      </cac:TaxSubtotal>    
  </cac:TaxTotal>
  
  
  <cac:TaxTotal>
      <cbc:TaxAmount currencyID="EUR">2048.44</cbc:TaxAmount>
  </cac:TaxTotal>
```
(taken from an XRechnung 2.0.1 example UBL creditnote - 
[ubl-cn-br-de-10-test-219-identity.log](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/5717059/ubl-cn-br-de-10-test-219-identity.log) (it's an XML))

Creates the following error with Saxon 10.3:
```
net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the second operand of '+' (2048.44, 2048.44)
```

The source of the rule is this:
```
  <param name="BR-CO-15" value="every $Currency in cbc:DocumentCurrencyCode satisfies (cac:LegalMonetaryTotal/xs:decimal(cbc:TaxInclusiveAmount) = round( (cac:LegalMonetaryTotal/xs:decimal(cbc:TaxExclusiveAmount) + cac:TaxTotal/xs:decimal(cbc:TaxAmount[@currencyID=$Currency])) * 10 * 10) div 100)"/>
```

To avoid the error, may using the `sum` function here should resolve the issue.

**Comment by oriol** [comment]
@phax,the second repetition of the TaxTotal is supposed to be in another currency. 

From the EN: The BT-111  Invoice total VAT amount in accounting currency

In the example, the second repetition of the TaxTotal has the same currency as the first one, and I think the solution is not summing up both values.

**Comment by phax** [comment]
Okay, so maybe you could add a rule that states, that no 2 top-level `TaxTotal` elements have the same `TaxAmount/@currencyID` ??

**Comment by oriol** [comment]
Added condition to check there is only one TaxTotal for each currency.

**Comment by BewanBC** [comment]
The consequence of this modification is that we can not specify the TaxTotal in the InvoiceLine level anymore, should we modify our software to avoid the use of TaxTotal in the invoiceLine ?

**Comment by oriol** [comment]
As far as I know, the EN does not allow TaxTotal in the InvoiceLine. You can specify the class ClassifiedTaxCategory within the Item of each InvoiceLine, but not TaxTotal per InvoiceLine.

**Comment by BewanBC** [comment]
ok thank you for your answer, we will remove the TaxTotal per InvoiceLine for BIS3. On the other hand we must keep it for UBLBE (until now UBLBE need the TaxTotal per InvoiceLine but maybe this could change in the next few days...)

**Comment by PatrickVHL** [comment]
@oriol this change has broken the SeeF (energy e-invoice) extension that is used in the Netherlands.
The extension contains a TaxTotalPerSupplierParty which references the TaxTotal.
Is it possible to make the xpath more specific to overcome this issue?

**Comment by PatrickVHL** [comment]
`<param name="BR-CO-15" value="every $Currency in cbc:DocumentCurrencyCode satisfies (count(cac:TaxTotal/xs:decimal(cbc:TaxAmount[@currencyID=$Currency])) eq 1) and (cac:LegalMonetaryTotal/xs:decimal(cbc:TaxInclusiveAmount) = round( (cac:LegalMonetaryTotal/xs:decimal(cbc:TaxExclusiveAmount) + cac:TaxTotal/xs:decimal(cbc:TaxAmount[@currencyID=$Currency])) * 10 * 10) div 100)"/>`

or 

`<param name="BR-CO-15" value="every $Currency in cbc:DocumentCurrencyCode satisfies (count(/*/cac:TaxTotal/xs:decimal(cbc:TaxAmount[@currencyID=$Currency])) eq 1) and (cac:LegalMonetaryTotal/xs:decimal(cbc:TaxInclusiveAmount) = round( (cac:LegalMonetaryTotal/xs:decimal(cbc:TaxExclusiveAmount) + cac:TaxTotal/xs:decimal(cbc:TaxAmount[@currencyID=$Currency])) * 10 * 10) div 100)"/>`

**Comment by rkottmann** [comment]
That could be the CII solution:

```xml
every $Currency  in rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode satisfies       
            (  count (
                   rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:TaxTotalAmount[@currencyID=$Currency]    ) eq 1 
              and  
              (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:GrandTotalAmount) 
                = round( 
                    (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:TaxBasisTotalAmount) + (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:TaxTotalAmount[@currencyID=$Currency]))) * 10 * 10) div 100)) or (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:GrandTotalAmount)     = (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:TaxBasisTotalAmount)
                    
       )
    )
```

But only did some first tests. More to follow.
