### ISSUE TITLE
Create checks, that the CII date format is verified

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#259]
Source: https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/56

Please check that the `format` attribute is only `102`, `610` or `616`

Check the `102` format like this:
* Length must be 8
* All chars must be numeric
* Year must be > 0
* Month must be >= 1 and <= 12
* Day must be >= 1 and <= 31

A regular expression for this may look like this:
```
^[0-9][0-9][0-9][1-9](1[0-2]|0[1-9])(3[01]|2[0-9]1[0-9]|0[1-9])$
```

**Comment by oriol** [comment]
Applying regular expression (20\d{2})(\d{2})(\d{2}) to udt:DateTimeString[@format = '102']

**Comment by phax** [comment]
I don't like the fix `20` in front. Wouldn't it be simpler (and less error prone) to use `\d{8}` instead?

**Comment by oriol** [comment]
You are right.
