### ISSUE TITLE
Block simultaneous use of BT-31 and BT-63

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#260]
If BG-11 _Seller tax representative party_ is present in an invoice, BT-63 S_eller tax representative VAT identifier_ is mandatory. BT-31 _Seller VAT identifier_ cannot be present at the same time. 
This rule is mentioned in the usage note to BT-31, but a corresponding validation rule is missing.

**Comment by oriol** [comment]
This rule is not explicitly stated in the EN.

Suggest not to add this validation rule.

**Comment by SLennartsson** [comment]
Why is the usage note to BT-31 disregarded/disqualified?

**Comment by oriol** [comment]
The usage note says "A VAT registered Supplier shall include his VAT ID except when he uses a tax representative.
My interpretation of this statement is that it is not required to have the VAT registered supplier VAT ID when there is a tax representative, but I do not interpret that it shall be prohibited. 
I will take that question to the TC 434 for clarification.

**Comment by SimonsPaul** [comment]
I tend to agree with Oriol. BR-S-2 states even and/or.

**Comment by SimonsPaul** [comment]
Agreed in WG1 to not implement the rule.
