### ISSUE TITLE
BT-69 should point to a restricted code set

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#261]
_Seller tax representative party_ may be used in a country where VAT is liable but the current Usage note for BT-69 _Tax representative country code_ refers to the full 3166-1 list of country codes. A restriction is needed so that only the applicable member states are listed (plus a consequential change of the accompanying validation rule)

**Comment by oriol** [comment]
The EN does not reflect the list of countries to the applicable member states, so I would suggest not restricting this list as it would require too much contents validation and beyond the EN itself.

Would suggest closing this issue.
