### ISSUE TITLE
No BG-11 when invoice is not subject to VAT

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#262]
BG-11 _Seller tax representative party_ has a meaning only in relation to the reporting/payment of VAT. 
If BT-118 _VAT category code_ indicates that the invoice is not subject to VAT, a validation rule should block use of BG-12.

**Comment by oriol** [comment]
This rule is not explicitly stated in the EN. Suggest not addressing this issue.

**Comment by SimonsPaul** [comment]
BG-12 is part of BG-11.
BR-O-2 states that shall not contain the seller VAT identifier. As this is a mandatory element 1..1 inside BG-11, it implies that the BG-11 can not be mentioned. This means obviously that it can not include BG-12 in my opinion. So testing on BG-11 does already do the job I suppose.

**Comment by SimonsPaul** [comment]
There is a typo in the request. It should state "block the use of GB-11".
Agreed that this is already tested. If an invoice is out of scope, the complete invoice is out of scope including omittance of VAT identifiers. The amendment will change this however.
