### ISSUE TITLE
BR-S-03: the rule differs in CII and UBL

### ISSUE THREAD

**Issue by OnlyDex** [ConnectingEurope/eInvoicing-EN16931#263]
With Issue #192 , BR-S-03 was changed in UBL so that only VAT is valid as TaxScheme. In the CII, FC (Seller tax registration identifier) is also allowed in addition to VAT.

`test="/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:SellerTradeParty/ram:SpecifiedTaxRegistration/ram:ID[@schemeID = ('VA', 'FC')]...`

In Germany it is possible to not have a VAT-ID, just a tax registration identifier. The best solution would be to add the tax registration identifier (FC) for UBL.
BTW the description of BR-S-03 doesn´t match anymore with the rule.

**Comment by OnlyDex** [comment]
in my opinion it´s a problem in UBL, not CII

**Comment by phax** [comment]
Its an inconsistency between the 2 of them - it's not me to decide ;-)

**Comment by oriol** [comment]
In the UBL binding, there is no "FC" code to define the Tax Registration Identifier (BT-32).  It is defined as "different from VAT". 
As there is not "FC" code, the validation rule BR-S-03 was applied only to VAT identifier and not to tax registration identifier. Should this rule be added in the UBL, it would be required to have a specific code for the Tax Registration Identifier first.

**Comment by midran** [comment]
The EN 16931 part 3-2 on UBL syntax binding, page 15. Defines for "Seller taxregistrationidentifier" BT-32 that the rule for qualifying the identifier is 

withcac:TaxScheme/cbc:ID ! = “VAT"

Consequently this is not a validation artifact development issue but is defined in the standardisation. Changes to this need to go through an amenement process by TC434

**Comment by SimonsPaul** [comment]
This topic shall be addressed in WG3.
