### ISSUE TITLE
[BR-05]-An Invoice shall have an Invoice currency code. - misleading?

### ISSUE THREAD

**Issue by seppbrathansel** [ConnectingEurope/eInvoicing-EN16931#27]
The Business rule error text is misleading because there is an invoice currency, but CUX:3:EUR:18 might be expected and is missing
	cen_edifact.EDIFACT_EXAMPLE1.report.xml
</G_SG2>	<G_SG7><S_CUX><C_C504>
		<D_6347>2</D_6347>	<D_6345>EUR</D_6345>
			</C_C504>
		</S_CUX>
	</G_SG7>	<G_SG8>	      <error xsi:type="BAR">
         <description>[BR-05]-An Invoice shall have an Invoice currency code.</description>
         <location>xml:2:0</location>
         <test>G_SG7/S_CUX/C_C504[D_6347='3' and D_6343='18']/D_6345</test>
      </error>
	e.g. Something like….Shall be used in combination with the Total VAT amount in accounting currency when the VAT accounting currency code differs from the Invoice currency code.

**Comment by AndreasPvd** [comment]
Hi sepp,
can you please show me where 
G_SG7/S_CUX/C_C504[D_6347='3' and D_6343='18']/D_6345

this comes from? It is not within the schematron rules.
Within the rules it is stated 

G_SG7/S_CUX/C_C504[D_6347='2']/D_6345

and that is correct.

Thank you.

**Comment by AndreasPvd** [comment]
Checking is correct.
