### ISSUE TITLE
BIS3 UBL XML Invoices: question about namespaces

### ISSUE THREAD

**Issue by skizub21** [ConnectingEurope/eInvoicing-EN16931#272]
Hello,
I have a question about document namespaces. According to all examples available they must be defined as:
**_xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" ..._**

so their corresponding usage in document will be:
_< cbc:ID >I0000001</cbc:ID>
< cbc:IssueDate >2021-03-08</cbc:IssueDate>_

Is it legal from EN16931 point of view to redefine namespaces? 

For example:
**_xmlns:myns1="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:myns2="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" ...._**
so usage in document will be:
_< myns2:ID >I0000001</myns2:ID>
< myns2:IssueDate >2021-03-08</myns2:IssueDate>_

In case it is possible will  schematron validation be able to validate document using different namespaces correctly?

**Comment by phax** [comment]
Yes this is totally valid.
The namespace prefixes (`cac`, `cbc`, `myns1`, `myns2`) are just "text replacements" for underlying namespace URLs (like `urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2`) - you can pick whatever prefix you like here, as long as the other URL is correct.

The problem is, that certain Schematron rules (not in this project) are written very badly and refer to a specific prefix. But from this project's point of view, it is totally fine to use whatever prefix you like. Small side note: please don't use the "default" prefix (empty String) as it has a special meaning.

hth, Philip

**Comment by skizub21** [comment]
Thank you Philip. 
I understand and fully agree that it is valid from XML document point of view. 

But if it is also valid from project point of view(PEPPOL, [eInvoicing), then EU validations
[should]https://www.itb.ec.europa.eu/invoice/upload produce same results, correct?

Below is a result of quick test I did (one of the files has customised names):
[customized-ns.pdf](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/6108419/customized-ns.pdf)
[standard-ns.pdf](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/6108421/standard-ns.pdf)

It produces different validation results I'm afraid...

**Comment by phax** [comment]
Weird - seems like a bug in their software.
Can you please try with https://ecosio.com/en/peppol-and-xml-document-validator/ - thx

**Comment by skizub21** [comment]
Philip, 
I'm getting exactly the same results when validating using Ecosio site.

![ecosio_modified](https://user-images.githubusercontent.com/78475687/110490475-a2fe1900-80f0-11eb-9fac-683acb32eb9d.png)
![ecosio_standard](https://user-images.githubusercontent.com/78475687/110490477-a396af80-80f0-11eb-8ad4-3ce0fb64165f.png)

To me file having non-standard names of namespaces is not being fully validated and produces much better results than the same file having standard (cac, cbc, etc) namespaces.

**Comment by phax** [comment]
@skizub21 are you able to send me the examples files via email? See https://github.com/phax/ for the address - I am curious :)

**Comment by oriol** [comment]
We haven't been able to reproduce this error. If you can upload an example that fails, we will reopen the issue.
