### ISSUE TITLE
CII Invoice Totals

### ISSUE THREAD

**Issue by skizub21** [ConnectingEurope/eInvoicing-EN16931#273]
I have a question regarding artefact for invoice totals (rule BG-22). Document defining all rules to apply to CII invoices EN-16931
says that <ram:SpecifiedTradeSettlementHeaderMonetarySummation> must be always present in invoice.

However when I validate an invoice without this node:
![totals3](https://user-images.githubusercontent.com/78475687/110952053-0b920380-8346-11eb-83e4-8203383995db.png)
validation returns SUCCESS

When an empty node is added:
![totals2](https://user-images.githubusercontent.com/78475687/110952179-32503a00-8346-11eb-8adc-d62962a41412.png)
validation returns FAILURE and complains about errors (BR-12, BR-13, etc).

Is that correct? Should not validation produce an error in first case as well?

**Comment by oriol** [comment]
When no SpecifiedTradeSettlementHeaderMonetarySummation present, BR-CO-15 will fire

**Comment by skizub21** [comment]
Hi Oriol,

As per my original email problem is that currently it does not.
Neither BR-CO-15 or any other error is being produced - we are getting
successful validation instead.

If you try to validate the file (with
SpecifiedTradeSettlementHeaderMonetarySummation node  commented out)
attached using https://www.itb.ec.europa.eu/invoice/upload, ecosio portal,
etc you'll get no error at all.
As soon as you specify an empty node
<SpecifiedTradeSettlementHeaderMonetarySummation/> it works as described by
you, but not in the first case.

**Comment by skizub21** [comment]
Hi Oriol,

Please ignore my previous email it was sent before I've seen ticket and
commit related on the portal.
