### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#274]
Seems like Travis has issues with pulling the Docker image:
https://travis-ci.org/github/ConnectingEurope/eInvoicing-EN16931/jobs/763161147

**Comment by oriol** [comment]
I did reach the pull rate limit.

**Comment by phax** [comment]
Is this a Docker issue or a Travis issue? Is Docker the right tool here?

**Comment by oriol** [comment]
https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=increase%20rate%20limit&utm_budget=

It is a docker issue, but I think we can live with their limits.

**Comment by phax** [comment]
Agree:
> The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.
