### ISSUE TITLE
Calculaton error

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#275]
Fatal error in BR-CO-16
--
Following issue was reported by Sören Lennartsson to the Peppol service desk but is concerned with an EN 16931 rule.

If BR-112, invoice total amount, exactly balances BT-113, prepaid amount, a fatal error is triggered. But if introducing a small BT-114 rounding amount the error may be avoided.

Two attached XML files illustrare this (apologies for all irrelevant metadata in the test files).

--
File extensions changed from xml to txt to enable uploading to GitHub.

[INVOICE--UBL-I-6_VAT_O+0,1___ NO_ERROR.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/6230630/INVOICE--UBL-I-6_VAT_O%2B0.1___.NO_ERROR.txt)
[INVOICE--UBL-I-6_VAT_O---ERROR.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/6230631/INVOICE--UBL-I-6_VAT_O---ERROR.txt)

**Comment by oriol** [comment]
This is already solved in 1.3.4 hot fix. Can you please check?
