### ISSUE TITLE
Coexistence of EmbeddedDocumentBinaryObject and ExternalReference in same Attachment node

### ISSUE THREAD

**Issue by juskoljo** [ConnectingEurope/eInvoicing-EN16931#276]
Hi,

I wonder is it a feature or bug that there can be `EmbeddedDocumentBinaryObject` and `ExternalReference` under the same `Attachment` node? All the documentation and examples are suggesting to have one at a time?

No validation errors is fired with below snippet:

```xml
<CreditNote
  xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
  xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
  xmlns="urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2">
  <cac:AdditionalDocumentReference>
    <cac:Attachment>
      <cbc:EmbeddedDocumentBinaryObject filename="milage.csv" mimeCode="text/csv">bWlsYWdlIHJlcG9ydA==</cbc:EmbeddedDocumentBinaryObject>
      <cac:ExternalReference>
        <cbc:URI>www.techspec.no</cbc:URI>
      </cac:ExternalReference>
    </cac:Attachment>
  </cac:AdditionalDocumentReference>
</CreditNote>
```

BR,
Jussi Koljonen

**Comment by oriol** [comment]
There is no explicit rule in the EN stating that you cannot use both, even if it could be a "best practice". 

I suggest sending this to the TC434 for consideration.

**Comment by juskoljo** [comment]
Thanks for quick response @oriol :)

**Comment by SimonsPaul** [comment]
There is a ballot going on for the Amendment. WG1 will meet again when the results are known. We will discuss this topic in the meeting.

**Comment by oriol** [comment]
Close and wait for the amendment.
