### ISSUE TITLE
Which document type to use when government is sending tax notifications?

### ISSUE THREAD

**Issue by dwillekens** [ConnectingEurope/eInvoicing-EN16931#281]
**Problem:**
Flemish government is ready to send out structured tax notifications (Peppol BIS v3 based) to Businesses (withholding tax, property tax, other debt claims & tax payment invitations, …). Document type to be used is certainly not 380 (= commercial invoice). Tax authorities in Belgium rejected also 383 (Debit note) as not suited for this kind of invoices. Code 388 could be used (as used in Finland) but is (as I understand it) reserved for “pure” tax (VAT) invoices.
**Proposal** (from UNTDID 1001): use
102 	Tax notification
           	Used to specify that the message is a tax notification
388 	Tax invoice
             	An invoice for tax purposes.
102	Not present in code list used in EN16931, not present Peppol
388	Present in code list used in EN16931, not present Peppol
**Suggestion**:
Use 102 for public entity taxes (e.g. withholding tax (and others as described above))
Use 388 for “pure” VAT invoices
**Proposed Decision**:
Step1: Add code 102 to CEF subset of UNCL1001
Step2: Code 102 and code 388 can be added to Peppol BIS v3 subset of the code list ‘1001’
Dirk Willekens
Senior Product Specialist
GS1 Belgium & Luxembourg
Galerie Ravensteingalerij 4 b10 
1000 Brussel - Bruxelles
T +32 (0)2 896 52 16		M +32 (0)475 36 65 19
E dwillekens@gs1belu.org

**Comment by SimonsPaul** [comment]
A discussion has been held in TC434/WG1. There was no objection for filing a request for adding a code.
That request has been filed at the CEF helpdesk in the meantime.
This will be discussed for the next codelist review due for the fall release.

**Comment by oriol** [comment]
Thank you @SimonsPaul. 

I am closing the issue as it will come back with the request for changes in the codelists from CEF for the fall release.
