### ISSUE TITLE
Rule UBL-SR-45 not working correctly

### ISSUE THREAD

**Issue by supportEdigard** [ConnectingEurope/eInvoicing-EN16931#283]
We have encountered validator error, this issue is related to PEPPOL BIS Billing 3.0 (Profile 01)

We have tried to validate CreditNote in https://anskaffelser.dev/service/validator/ and we have received validation error.

![image](https://user-images.githubusercontent.com/82653333/115016981-83f86100-9ebe-11eb-9a9d-50c9c6aecd1c.png)

```
UBL-SR-45 Due Date shall occur maximum once
/cn:CreditNote[1]
Test: (count(cac:PaymentMeans/cbc:PaymentDueDate) <=1)
```

According to documentation validation should pass.

![image](https://user-images.githubusercontent.com/82653333/115017072-a12d2f80-9ebe-11eb-9491-e193ef9c9fb7.png)

https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-creditnote/cac-PaymentMeans/

Data file with failed validation:
​
![image](https://user-images.githubusercontent.com/82653333/115017091-a9856a80-9ebe-11eb-9c8c-b2825ffe1985.png)

Please assist us in this case, please notify when validator will be updated, we will do adjustments in our system afterwards.

**Comment by phax** [comment]
Do you eventually have a test file you can share here?

**Comment by oriol** [comment]
As defined in the EN semantic data model, the Payment Due Date BT-9 can be only stated once. The fact that the binding to UBL allows technically to add it twice does not mean that this is allowed, and that's why UBL-SR-45 is defined.
