### ISSUE TITLE
Requesting to remove UBL-SR-27 and UBL-SR-38 as the syntax does not exist in BIS Billing

### ISSUE THREAD

**Issue by UrsuliH** [ConnectingEurope/eInvoicing-EN16931#287]
Requesting to remove these two rules as the syntax does not exist in BIS Billing:

a. “UBL-SR-27 Payment means text shall occur maximum once”
This rule references cac:PaymentMeans/cbc:InstructionNote – however this does not exist BIS Billing syntax.

b. “UBL-SR-38 Invoiced item VAT exemption reason text shall occur maximum once”
This rule references cac:Item/cac:ClassifiedTaxCategory/cbc:TaxExemptionReason – however this does not exist BIS Billing syntax.

**Comment by oriol** [comment]
UBL-SR-27 corrected to point to cbc:PaymentMeansCode.
UBL-SR-38 removed.

**Comment by klakegg** [comment]
Did this issue ended up removing a validation rule related to EN16931 because it is not needed in the Peppol BIS Billing 3.0 specification?

**Comment by oriol** [comment]
It is an unnecessary rule because of UBL-CR-601.
