### ISSUE TITLE
BR-CL-11 update Usage

### ISSUE THREAD

**Issue by UrsuliH** [ConnectingEurope/eInvoicing-EN16931#288]
In the Peppol online doco, [BR-CL-11](https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-tc434/BR-CL-11/) context is cac:PartyLegalEntity/cbc:CompanyID[@schemeID] (which is correct), however the Usage under the rule is incorrect as it doesn’t mention cac:PartyLegalEntity.

Suggested changes for both ubl:Invoice and ubl:CreditNote:
**remove:**
cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID
cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID
**add:**
cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyID
cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyID
(and keep cac:PayeeParty/cac:PartyLegalEntity/cbc:CompanyID)

**Comment by oriol** [comment]
This is a remark for the Peppol team and its documentation.

**Comment by midran** [comment]
Adopted to Peppol POAC as issue POACC-425
