### ISSUE TITLE
Rule BR-CO-09

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#289]
1A and XI has been added in the ISO3166 lists, but not for the BR-CO-09 rule for the VAT identifier as consequence VAT identifiers prefixed with either code trigger a fatal error. Reported to Peppol service desk as issue PEPPOL-4147.

**Comment by phax** [comment]
The list says "alpha-2" code. Why would the value "1A" be added? According to Wikipedia the proposed country code for Kosovo is "XK" - can we please check the sources?

**Comment by midran** [comment]
The code 1A was used instead of XK by request of the Official Journal of the EU because it is the code used within the EU to identify Kosovo. Note that this code was added as extension to the 3166 code list one year ago and done through normal procedures. This issue is not to add any country codes but to update validation rule BR-CO-09 to support all codes.

**Comment by phax** [comment]
Okay thank you. I am pretty sure, that will break a lot of existing regular expressions in the form `[A-Z]{2}` so I think having an explicit test files for BOTH country codes would REALLY be helpful!
