### ISSUE TITLE
UBL rule: BR-AE-01 not firing as expected

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#3]
The rule states
An Invoice that contains a line, a document level allowance or a document level  charge where the Invoiced item VAT category code (BT-151, BT-95 or BT-102) is “Reverse charge” shall contain in the VAT breakdown (BG-23) exactly one VAT category code (BT-118) equal with "Reverse charge".

It does not seem that the validation checks for only one instance in TaxTotal/TaxSubtotal/TaxCategory.

**Comment by oriol** [comment]
((exists(//cac:TaxCategory/cbc:ID[. = 'AE']) or exists(//cac:ClassifiedTaxCategory/cbc:ID[. = 'AE'])) and (count(//cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory) = 1) and (count(//cac:TaxCategory/cbc:ID[. != 'AE']) = 0 and count(//cac:ClassifiedTaxCategory/cbc:ID[. != 'AE'])=0)) or (count(//cac:TaxCategory/cbc:ID[. = 'AE']) = 0 and count(//cac:ClassifiedTaxCategory/cbc:ID[. = 'AE'])=0)

**Comment by SiwMeckelborg** [comment]
Test nr 3 in unit test of BR-AE-01 does not fire as expected, please review xPath in this validation rule.
