### ISSUE TITLE
[BR-CO-02]-Account identification shall be       present if payment means is credit transfer. 

### ISSUE THREAD

**Issue by seppbrathansel** [ConnectingEurope/eInvoicing-EN16931#30]
Why does this check fails? the Account ID is there and if I even add a value for the NAD+SE_C088/3434 (=instition branch identifier) as mentioned in the schematron rule it still fails. B ut even if it would not fail, is the check really correct requiring the 3434?

edited sample string: FII+RB+SE1212341234123412+SEXDABCD:::TEST'

<failed-assert id="BR-CO-02" location="/M_INVOIC" test="((G_SG8[S_PYT/D_4279='1']/S_PAI/C_C534/D_4461 = ('30','57')) and (G_SG2[S_NAD/C_C082/D_3039='PE' or S_NAD/C_C082/D_3039='SE']/S_FII[D_3035='RB']/C_C088/D_3434)) or not(G_SG8[S_PYT/D_4279='1']/S_PAI/C_C534/D_4461 = ('30','57'))" flag="fatal">
        <text>[BR-CO-02]-Account identification shall be
      present if payment means is credit transfer. </text>
    </failed-assert>

**Comment by seppbrathansel** [comment]
example:

UNA:+.?*'UNB+UNOW:4::7+4000001000005:14+4000001000005:14+20130513:1403+87846595'UNH+INVOICE_test_7+INVOIC:D:14B:UN::16B'BGM+380+INVOICE_test_7++++'DTM+137:20130513:102'DTM+167:20130101:102'DTM+168:20131231:102'FTX+AAB+++Payment within 30 days'FTX+GEN+++Testscenario 7'FTX+DOC++P1+urn?:cen.eu?:en16931?:2017'FTX+AGM+++Tax'RFF+ON:Order_9988_x'NAD+SE+5532331183:++The Sellercompany Incorporated:Civic Service Centre+Main street 2, Building 4+Big city++54321+SE'FII+RB+SE1212341234123412+SEXDABCD:::TEST'FII+RB+SE1212341234123412'CTA+SU+:Anthon Larsen'COM+4698989898:TE'COM+Anthon@SellerCompany.se:EM'NAD+BY+++THe Buyercompany+Anystreet 8:Back door+Anytown+:::RegionB+101+SE'CTA+SU+:3150bdn'COM+5121230:TE'COM+john@buyercompany.no:EM'CUX+2:SEK'PYT+1'PAI+::30'LIN+1'PIA+5+RT3000:SA'IMD+F++:::Road tax'IMD+A++:::Weight-based tax, vehicles >3000 KGM'QTY+47:1:C62'MOA+203:2500'PRI+AAA:2500::::'RFF+ON::1'TAX+7+VAT+++:::+O'LIN+2'PIA+5+REG:SA'IMD+F++:::Road Register fee'IMD+A++:::Annual registration fee'QTY+47:1:C62'MOA+203:700'PRI+AAA:700::::'TAX+7+VAT+++:::+O'UNS+S'MOA+79:3200'MOA+389:3200'MOA+388:3200'MOA+9:3200'TAX+7+VAT+++:::+O'MOA+125:3200'MOA+124:0'UNT+49+INVOICE_test_7'UNZ+1+INVOICE_test_7'

**Comment by phax** [comment]
We wait on the outcome of #26 and #27

**Comment by AndreasPvd** [comment]
Testing your example again with the current versions of schematron and conversion files do not bring errors any more
