### ISSUE TITLE
[CL-10]-Payment means in an invoice MUST be coded using UNTDID 4461 restricted code       list

### ISSUE THREAD

**Issue by seppbrathansel** [ConnectingEurope/eInvoicing-EN16931#31]
I tried to fill the PAI_4461 with several codes (53,58,60), but still get this error. How does this check work?
e.g.: PAI+::53'

 <failed-assert location="/M_INVOIC/G_SG8[1]/S_PAI/C_C534/D_4461" test="((not(contains(normalize-space(.), ' ')) and contains(' 10 20 30 31 48 54 55 57 58 97 98 ', concat(' ', normalize-space(.), ' '))))" flag="fatal">
        <text>[CL-10]-Payment means in an invoice MUST be coded using UNTDID 4461 restricted code
      list</text>
    </failed-assert>

**Comment by phax** [comment]
According to the EN only certain codes are allowed: 30, 57 and 49 (in one form or the other)
So no further action on our side.
https://www.unece.org/trade/untdid/d16b/tred/tred4461.htm
