### ISSUE TITLE
UBL Mapping - "xs" prefix mapping is missing

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#33]
The same error as in https://github.com/OpenPEPPOL/peppol-bis/pull/38 also applies to the UBL Schematrons in here.
Just add `<ns prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>` in the overall XSD to fix the issue.

**Comment by oriol** [comment]
Resolved
