### ISSUE TITLE
EDIFACT issue with BR-CO-10

### ISSUE THREAD

**Issue by seppbrathansel** [ConnectingEurope/eInvoicing-EN16931#37]
I hope I'm not stupid but I looked several times on in the message to find the issue but couldn't find it.
There is just one net amount on line item and should be same as on total level (both 100).
What am I doing wrong? Why I do get:

    <failed-assert id="BR-CO-10" location="/M_INVOIC[1]" test="G_SG52/S_MOA/C_C516[D_5025='79']/D_5004 = (round(sum(/M_INVOIC/G_SG27/G_SG28/S_MOA/C_C516[D_5025='203']/D_5004) * 10 * 10)div 100)" flag="fatal">
        <text>[BR-CO-10]-Sum of Invoice line net amount =
      Σ Invoice line net amount. </text>
    </failed-assert>

![grafik](https://cloud.githubusercontent.com/assets/25059758/23547892/43150bcc-0005-11e7-96fb-c1d768f53770.png)

message:
UNA:+.?*'
UNB+UNOW:4::7+4000001000005:14+4000001000005:14+20150109:1403+87846595'
UNH+1234+INVOIC:D:96A:UN:EAN008'
BGM+380+645643837+9'
DTM+137:20160712:102'
DTM+35:20161012:102'
ALI+++11'
RFF+AAU:2233'
DTM+171:20161011:102'
RFF+ON:4455'
DTM+171:20160610:102'
RFF+VN:8877'
DTM+171:20160712:102'
NAD+BY+5790000000005::9'
RFF+XA:DK10629845'
NAD+DP+5790002330278::9'
RFF+XA:DK23876588'
NAD+SU+5790000000012::9'
RFF+XA:DK10687672'
NAD+IV+5790002330322::9'
RFF+XA:DK98767890'
TAX+7+VAT+++:::25+S'
CUX+2:DKK:4'
PAT+3'
DTM+13:20161112:102'
ALC+C++++ADR'
MOA+8:20'
LIN+1++5776565423456:EN::'
QTY+47:50:KGM'
QTY+46:51:KGM'
QTY+192:1:KGM'
MOA+203:100'
PRI+AAA:20:::10:KGM'
TAX+7+VAT+3010::9DK++:::25+S'
MOA+124:25'
TAX+7+VAT+3010::9DK++:::25+S'
MOA+125:100'
UNS+S'
CNT+2:1'
MOA+79:100'
MOA+86:275'
MOA+125:220'
MOA+131:20'
MOA+176:55'
TAX+7+VAT+3031::9DK++:::25+S'
MOA+124:55'
MOA+125:220'
UNT+49+1234'
UNZ+1+12115118'

**Comment by seppbrathansel** [comment]
Now I tested this again with the offline / Java validator and it worked without any error, but the GITB validator still reports a general one:
`
"Failed to validate file [cen_edifact.EDIFACT_EXAMPLE.txt]: Error creating bean with name 'XMLValidator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Unable to convert input file"
`

**Comment by phax** [comment]
Hi!
I need to update the test routines from the separate java-tools project into this project...

// Philip

**Comment by seppbrathansel** [comment]
ok fine. just let me know when this is done;)

**Comment by phax** [comment]
@seppbrathansel will do - expect it to be at the latest tomorrow.
Btw. do we have a meeting on Wed?

**Comment by seppbrathansel** [comment]
Thanks, I think CEN meetings are over now;)

**Comment by phax** [comment]
@seppbrathansel Please re-check - I updated all the tools to be consistent

**Comment by phax** [comment]
@seppbrathansel  Any update from your side?
