### ISSUE TITLE
VA instead of VAT in BR-S-02 UBL?

### ISSUE THREAD

**Issue by MatteoJoliveau** [ConnectingEurope/eInvoicing-EN16931#38]
In the UBL rule BR-S-02 the TaxScheme ID is verified to be "VA", while it has always been "VAT"

Is it a typo or is it correct? Because now our nvoices with cac:TaxScheme/cbc:ID = 'VAT' are failing validation.

```xml
<param name="BR-S-02" value="(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'S']) and (exists(//cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = ('VA', 'FC')]/cbc:CompanyID) or exists(//cac:TaxRepresentativeParty/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID = 'VA']/cbc:CompanyID))) or not(exists(//cac:ClassifiedTaxCategory[normalize-space(cbc:ID) = 'S']))"/>
```

**Comment by phax** [comment]
The underlying codelist is UNTDID 1153 D16B and this one states "VA" is the correct one - https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred1153.htm

But there are other rules that still reference 'VAT':
```
  <param name="UBL-SR-12" value="(count(cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID='VAT']/cbc:CompanyID) &lt;= 1)"/>
  <param name="UBL-SR-13" value="(count(cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/cbc:ID!='VAT']/cbc:ID) &lt;= 1)"/>
```

**Comment by oriol** [comment]
You are right 

I need to upload the Syntax Rules, not yet there….

Oriol

**Comment by oriol** [comment]
We  follow the UNTDID 1153 codelist that uses "VA" instead of "VAT". The SR rules need to be corrected.

**Comment by phax** [comment]
Please close when commit is present - thx :)

**Comment by oriol** [comment]
Solved

**Comment by sarafacchinetti** [comment]
In the EN 16931-1:2017 the UNTDID 1153 is referenced only in BT-18 and BT-128.
Is this indication only for the mapping with UBL 2.1 (TS 16931-3-2)?

UNTDID 1153 looks appropriate (VA: VAT registration number) for cac:TaxScheme/cbc:ID in the BT-31 (Seller VAT id) and BT-48 (Buyer VAT id).
Why is it also used in BG-30 (Line VAT information) and in BG-23 (VAT breakdown) where we are not talking about a VAT registration number but simply the VAT ? (UNTDID 5153 is used in some old example -> VAT: Value added tax)

**Comment by oriol** [comment]
cac:TaxScheme/cbc:ID is not defined in the Norm, but it is required in the UBL syntax. That's why it has been included in the syntax binding. 

The use of VA instead of VAT is just for consistency with BT-18 and BT-128, avoiding people using "VA" in one place and "VAT" in another one.
