### ISSUE TITLE
UBL rules: BR-AE-03 & 04

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#4]
The final check in these two rules are 
or not(exists(//cac:ClassifiedTaxCategory[cbc:ID = 'AE']))

This should be changed to 
or not (exists(//cac:AllowanceCharge[cbc:ChargeIndicator='false']/cac:TaxCategory[cbc:ID = 'AE']))

**Comment by oriol** [comment]
Fixed as suggested

**Comment by SiwMeckelborg** [comment]
This is also found for BR-E-03 and 04. Please review all "similar" rules and ensure they are checking correct element.
