### ISSUE TITLE
BR-O-02 - VAT IDs for invoice not subject to vat

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#40]
In validation/ubl/schematron/UBL/EN16931-UBL-model.sch there are BR-O-02, BR-O-03, BR-O-04 which forbid the usage of Seller VAT ID or Seller tax representative VAT ID or Buyer VAT ID according to the rules defined in EN 16931-1:2017

"BR-O-2 “An Invoice that contains a line where the Invoiced item VAT category code (BT-151) is “Not subject to VAT” **shall not contain** the Seller's VAT identifier (BT-31), the Seller tax representative VAT identifier (BT-63) or the Buyer's VAT identifier (BT-46)”.

Wondering why "shall not".  "could not" probably is more appropriate.

This is not an issue of the schematron code. It is just to remember that a discussion about this topic could take place.

**Comment by oriol** [comment]
The severity on the rules is defined in the EN, not in the artefacts.

**Comment by SiwMeckelborg** [comment]
This is an issue for the EN itself, not the syntax bindings

**Comment by phax** [comment]
The change from "SHALL NOT" to "SHOULD NOT" would be a change in the EN itself and such cannot be done easily until the EN is revised. You need to wait until 2022, until the EN is revised. Sorry.
It was brought to the attention to WG1 and as such I'm closing this.
