### ISSUE TITLE
BT-21 Invoice subject note

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#41]
According to EN 16931-1 BT-21=Invoice note subject code (The subject of the textual note in BT-22)->
To be chosen from the entries in UNTDID 4451

How is this field mapped to UBL? Is the following example correct?

```
BT-21 -> <cbc:Note>#AAA#</cbc:Note>
where AAA= Goods item description in UNTDID 4451
```

It looks like BR-CL-19 is the business rule related to BT-21 but in EN16931-UBL-codes.sch it refers to Code allowance reason and in UBL\EN16931-UBL-model.sch it contains numbers instead of the 3 chars of UNTDID 4451.

Could you please have a check?

**Comment by sarafacchinetti** [comment]
ok, code list 4451

**Comment by AndreasPvd** [comment]
Can you please show a complete example of how to use BT-21?
Accoring to the TS is is stated "...for the **following textual** note". 
How to interpret this?

Is the first variant correct:

`<cbc:Note>#AAA#Human readable description line one</cbc:Note>`
`<cbc:Note>#AAA#Human readable description line two</cbc:Note>`
`<cbc:Note>No subject code</cbc:Note>`
`<cbc:Note>#BBB#Human readable description other subject code</cbc:Note>`

or the second one?

`<cbc:Note>#AAA#</cbc:Note>`
`<cbc:Note>Human readable description line one</cbc:Note>`
`<cbc:Note>Human readable description line two</cbc:Note>`
`<cbc:Note>##</cbc:Note> <!-- this should bring an error, but how to -deactivate- subject code again -->`
`<cbc:Note>No subject code</cbc:Note>`
`<cbc:Note>#BBB#</cbc:Note>`
`<cbc:Note>Human readable description other subject code</cbc:Note>`

**Comment by oriol** [comment]
Even if the cardinality of cbc:Note in UBL is 0..n, this is just for translation purposes: UBL has unbounded textual elements to allow for translating the text in different languages, but not to provide for an unbounded set of data elements. 

In this case, there is a cardinality mismatch with the Norm: the Norm allows for a group of unbounded notes and in UBL you shall group them into a single cbc:Note element. 

Regading your examples, the one that would fit is:

`<cbc:Note>#AAA#Textual note</cbc:Note>`

in case there is a code

or 

`<cbc:Note>Textual note</cbc:Note>`

when there is no code.
