### ISSUE TITLE
BT-18 Invoiced object identifier

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#42]
According to EN 16931-1 BT-18=Invoiced object identifier (An identifier for an object on which the invoice is based, given by the Seller). It may be a subscription number, telephone number, meter point, vehicle, person etc., as applicable.
0..1 Scheme identifier =The identification scheme identifier of the Invoiced object identifierIf it may be not clear for the receiver what scheme is used for the identifier, a conditional scheme identifier should be used that shall be chosen from the UNTDID 1153 code list entries.

How BT-18 is mapped to UBL and which business rules should it respect?

**Comment by oriol** [comment]
the rule implementing this restriction is BR-CL-07.

**Comment by sarafacchinetti** [comment]
UBL syntax binding is:
BT-18 mapped to "/Invoice/cac:AdditionalDocumentReference/cbc:ID"
with cbc:DocumentTypeCode=130

Where does "130" value come from?

**Comment by oriol** [comment]
Used DocumentTypeCode to differentiate BT-18 from other additional documents in BG-24

We use this element from UNCL 1001 130 | Invoicing data sheet
