### ISSUE TITLE
Implementation of Rule CL-01

### ISSUE THREAD

**Issue by kpetersdms** [ConnectingEurope/eInvoicing-EN16931#43]
It seem that the test for CL-01 is wrong. I used the rule via the kosit-validator and it said that the type code 380 (commercial invoice) ist wrong. But this is an allowed value for an invoice.
It seems that the test 
test="((not(contains(normalize-space(.), ' 80 ... 935 ')) and contains('  ', concat(' ', normalize-space(.), ' '))))"
should be 
test="((not(contains(normalize-space(.), ' ')) and contains(' 80 ... 935 ', concat(' ', normalize-space(.), ' '))))"
as the other tests, e.g. for CL-03 or CL-04.

**Comment by oriol** [comment]
The test is correct in github. Do you have the latest  version? It was corrected three months ago.

**Comment by phax** [comment]
@fbuettner-hb there are existing artefacts that maintain the latest EN 16931 validation rules: https://github.com/phax/ph-bdve/tree/master/ph-bdve-en16931

**Comment by fbuettner-hb** [comment]
@phax Thanks a lot! Actually, we had already updated the XSLT stylesheets in https://github.com/itplr-kosit/validationtool, but had not yet created a new release.
