### ISSUE TITLE
CII CL-01

### ISSUE THREAD

**Issue by LRabeDE** [ConnectingEurope/eInvoicing-EN16931#44]
Currently none of the existing codes of the UNTDID 1001 code list will be accepted. It seems that the correction which has been done in UBL regarding the document type code needs also to be done for the CII validation artefacts.

**Comment by phax** [comment]
Martin found the reason:

> When I looked at this issue, I found that the implementation of the xpath function “contains“ is wrong.
> It should be:
contains(' 80 81 82 83 84 130 202 203 204 211 261 262 295 296 308 325 326 380 381 383 384 385 386 387 388 389 390 393 394 395 396 420 456 457 458 527 575 623 633 751 780 935 ', normalize-space(.))
>
> Not :
> contains(normalize-space(.), ' 80 81 82 83 84 130 202 203 204 211 261 262 295 296 308 325 326 380 381 383 384 385 386 387 388 389 390 393 394 395 396 420 456 457 458 527 575 623 633 751 780 935 ')

So the parameter order is incorrect

**Comment by phax** [comment]
According to an email from Andreas, I'm allowed to change it
