### ISSUE TITLE
BR-CL-17 and BR-CL-18 don't consider S and AA

### ISSUE THREAD

**Issue by phax** [ConnectingEurope/eInvoicing-EN16931#45]
Short question:
Shouldn't the code list checks for BR-CL-17 and BR-CL-18 not also contain e.g. "AA" and "S" according to https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5305.htm ??

Thanks,
  Philip

**Comment by oriol** [comment]
"S" is already in the validation artefacts. 
"AA" is not but the point is that it is not defined in the EN.
