### ISSUE TITLE
UBL rules: Several VAT rules checking for non existing element

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#5]
Several of the VAT rules are having the following check:
[**cac:TaxCategoryCode**/cbc:ID='XX']

The element TaxCategoryCode is not existing in the mapping, please check all rules and change all to   [**cac:TaxCategory**/cbc:ID='XX']

**Comment by oriol** [comment]
Fixed
