### ISSUE TITLE
BR-CL-24 UBL - mimeCode - typo in list BT-125

### ISSUE THREAD

**Issue by jurajmarkovic** [ConnectingEurope/eInvoicing-EN16931#52]
Hello,

we have found typo in mimeCode list:

`<rule context="@mimeCode" flag="fatal">
    <assert
      test="((. = 'application/pdf' or . = 'image/png' or . = 'image/jpeg' or . = 'text/csv' or . = 'application/vnd.openxmlformats-officedocument. spreadsheetml.sheet' or . = 'application/vnd.oasis.opendocument.spreadsheet'))" id="BR-CL-24"
      flag="fatal">[BR-CL-24]-For Mime code in attribute use MIMEMediaType.</assert>
  </rule>`

There is an extra space in "application/vnd.openxmlformats-officedocume**nt. sp**readsheetml.sheet"
Small one, but needs correction
BR

**Comment by oriol** [comment]
corrected by @klakegg
