### ISSUE TITLE
BG-1 INVOICE NOTE in CII

### ISSUE THREAD

**Issue by LRabeDE** [ConnectingEurope/eInvoicing-EN16931#54]
Rules in CII Schematron are for my understanding not correct. With respect to the EN 16931-1 an INVOICE NOTE group might occure 0..n times.

The following structure (attached you will find a complete document) seems to me conform to the syntax binding but leads to a warning during validation ([CII-SR-029] - IncludedNote should exist maximum once):
```xml
    <rsm:ExchangedDocument>
        <ram:ID>123456</ram:ID>
        <ram:TypeCode>380</ram:TypeCode>
        <ram:IssueDateTime>
            <udt:DateTimeString format="102">20160621</udt:DateTimeString>
        </ram:IssueDateTime>
        <ram:IncludedNote>
            <ram:Content>Bei Fragen zu Ihrer Rechnung wenden Sie sich bitte an unseren Kundenserivce. Sie erreichen uns per Email: […], Tel.: […] oder Fax: […]</ram:Content>
            <ram:SubjectCode>ADU</ram:SubjectCode>
        </ram:IncludedNote>
        <ram:IncludedNote>
            <ram:Content>Die Lieferung erfolgt aufgrund der AGB […] erhältlich unter […]. Auf Wunsch senden wir sie auch zu.</ram:Content>
            <ram:SubjectCode>ADU</ram:SubjectCode>
        </ram:IncludedNote>
        <ram:IncludedNote>
            <ram:Content>Hinweis gemäß § 33 BDSG: Kundendaten werden gespeichert.</ram:Content>
            <ram:SubjectCode>ADU</ram:SubjectCode>
        </ram:IncludedNote>
        <ram:IncludedNote>
            <ram:Content>Beschädigt eingehende Sendungen bitte sofort beim Spediteur bzw. Paketdienstleister reklamieren. Genehmigte Rücksendungen schicken Sie bitte mit den Unterlagen an: […]</ram:Content>
            <ram:SubjectCode>ADU</ram:SubjectCode>
        </ram:IncludedNote>
    </rsm:ExchangedDocument>
```
[01.02a-INVOICE_uncefact.zip](https://github.com/CenPC434/validation/files/1716390/01.02a-INVOICE_uncefact.zip)

**Comment by phax** [comment]
You can easily resolve it like this:
```xml
        <ram:IncludedNote>
            <ram:Content>Bei Fragen zu Ihrer Rechnung wenden Sie sich bitte an unseren Kundenserivce. Sie erreichen uns per Email: […], Tel.: […] oder Fax: […]
Die Lieferung erfolgt aufgrund der AGB […] erhältlich unter […]. Auf Wunsch senden wir sie auch zu.
Hinweis gemäß § 33 BDSG: Kundendaten werden gespeichert.
Beschädigt eingehende Sendungen bitte sofort beim Spediteur bzw. Paketdienstleister reklamieren. Genehmigte Rücksendungen schicken Sie bitte mit den Unterlagen an: […]</ram:Content>
            <ram:SubjectCode>ADU</ram:SubjectCode>
        </ram:IncludedNote>
```

You can use multiline comments :)

**Comment by LRabeDE** [comment]
ok, this is a solution but this is not realy adressing the issue; which is, that both EN16931 (semantic data model and syntax binding) and underlaying syntac allows the usage of more than one invoice note (BG-1) which is not possible with the existing validation artefacts.

**Comment by phax** [comment]
Agree - bug in the rules. BG-1 allows for 0..n `IncludedNote` elements. And I couldn't find a reference to `CII-SR-029` in the specs....

My idea here: remove rule `CII-SR-029` - any objections.

**Comment by LRabeDE** [comment]
Agreed, but... we should also change the context of `CII-SR-030` from `Exchanged_Document` to `Exchanged_Document/IncludedNote`

**Comment by phax** [comment]
Okay, but both are bugs in the rules only. No changes needed in the Specs.
