### ISSUE TITLE
BT-82 payment means text

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#56]
This BT in UBL should be mapped to /Invoice/cac:PaymentMeans/cbc:PaymentMeansCode/@Name according to CEN TS 16931-3-2.

Could you please provide me an example of ubl code because I could not find an attribute @Name in cbc:PaymentMeansCode?

**Comment by phax** [comment]
The `name` attribute is part of the base type `{urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2}CodeType`
hth

**Comment by phax** [comment]
Got the okay from @sarafacchinetti  to close the issue
