### ISSUE TITLE
new ICD value is added into ISO 6523 ICD list – Estonian company code 0191

### ISSUE THREAD

**Issue by boerchr** [ConnectingEurope/eInvoicing-EN16931#58]
All, 
Support received the following : 
"Please be informed new ICD value is added into ISO 6523 ICD list – Estonian company code 0191
Currently it's not possible to use this ICD value in e-invoice, please make required modifications in e-invoice validators etc."

Would this mean artefacts have to be changed ?
Kind regards

**Comment by oriol** [comment]
Added in the Schematrons

**Comment by phax** [comment]
I assume this effects CII and EDIFACT as well...

**Comment by phax** [comment]
Finally in EDIFACT and CII as well

**Comment by klakegg** [comment]
Where may I find the respective page from the ICD list?

**Comment by phax** [comment]
Voila: 
[ICD_certificate_0191--20180131132855.pdf](https://github.com/CenPC434/validation/files/2045039/ICD_certificate_0191--20180131132855.pdf)

**Comment by klakegg** [comment]
Thank you. :)
