### ISSUE TITLE
BR-Z-10

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#59]
Performing some test in ubl this rule seems not to work if <cbc:TaxExemptionReason> is present in case of zero rated category. Could you please verify it?

**Comment by sarafacchinetti** [comment]
Replace with assert test="not((cbc:TaxExemptionReason) or  (cbc:TaxExemptionReasonCode))"

**Comment by phax** [comment]
will check. Thanks

**Comment by oriol** [comment]
Implemented
