### ISSUE TITLE
BR-AF-05 in contradiction with message text

### ISSUE THREAD

**Issue by rkottmann** [ConnectingEurope/eInvoicing-EN16931#60]
In [EN16931-CII-model.sch](/CenPC434/validation/blob/e93025c18c9e5ed482f00c8c78bd1a1479f534ee/cii/schematron/CII/EN16931-CII-model.sch) the XPath definition is greater zero
```xml
<param name="BR-AF-05" value="ram:RateApplicablePercent &gt; 0"/>
```

But the error message in  [EN16931-CII-model.sch](/CenPC434/validation/blob/e93025c18c9e5ed482f00c8c78bd1a1479f534ee/cii/schematron/abstract/EN16931-CII-model.sch)  states equals or greater zero

```xml
<assert test="$BR-AF-05" flag="fatal" id="BR-AF-05">
     [BR-IG-05]-In an Invoice line (BG-25) where the Invoiced item
     VAT category code (BT-151) is "IGIC" the invoiced item VAT rate (BT-152)
     shall be 0 (zero) or greater than zero.
</assert>
```

This seems to be a bug either in the test or the message.

**Comment by phax** [comment]
Thanks for pointing that out.
