### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#66]
Any information on when we can expect a new release of the validation artefacts?

**Comment by phax** [comment]
We have a meeting next week (15./16. of May) where a decision will be made. Stay tuned. Sorry for the delay.

**Comment by phax** [comment]
I got the name of a guy to help us with the Edifact artefacts. Will keep you posted once stuff is done.

**Comment by phax** [comment]
Good news. The release 1.1 of UBL and CII is planned for June 25th. finally 😆

**Comment by phax** [comment]
The release is here: https://github.com/CenPC434/validation/releases/tag/validation-1.1.0
