### ISSUE TITLE
Issue when using // in contexts

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#67]
I've found a whole set of issues which all comes from the same type of way of using xpaths in rules or contexts.

Many rules have a context or test expression which could look like this:

```
every $taxcurrency in cbc:TaxCurrencyCode satisfies exists(//cac:TaxTotal/cbc:TaxAmount[@currencyID=$taxcurrency])
```

That assumes that there is only one occurence of `//cac:TaxTotal/cbc:TaxAmount`. However, `TaxTotal` can be used on both header and line level in UBL and the result from the xpath is a list of nodes rather than an element so the XSLT fails.

This problem can be found in many places, probably both in CII and UBL. All rules which have `//element` where the element is either repeatable or can occur on different locations must be redesigned.

**Comment by phax** [comment]
I agree, that is something that authors should consider.
I don't see the need to necessarily change it, but at least to evaluate it.
In general, `//` should be avoided, because it is slow at execution time

**Comment by MartinForsberg-Ecru** [comment]
my example was not really very good. here is another:
(//cac:TaxTotal/cbc:TaxAmount[@currencyID = //cbc:DocumentCurrencyCode] and (string-length(substring-after(//cac:TaxTotal/cbc:TaxAmount[@currencyID = //cbc:DocumentCurrencyCode],'.'))&lt;=2)) or (not(//cac:TaxTotal/cbc:TaxAmount[@currencyID = //cbc:DocumentCurrencyCode]))

where the substring function fails as it expects a string value and not a node list

**Comment by MartinForsberg-Ecru** [comment]
@phax problem is that typical PEPPOL BIS v2 invoices causes the xslt to crash when being validated.

**Comment by phax** [comment]
@MartinForsberg-Ecru can you please paste an example invoice here. thx

**Comment by MartinForsberg-Ecru** [comment]
[Use Case M-A-X - Invoice_4A - kopia.txt](https://github.com/CenPC434/validation/files/2009179/Use.Case.M-A-X.-.Invoice_4A.-.kopia.txt)

(just noticed that the file fails xsd validation, but that doens't affect the issue as such

**Comment by phax** [comment]
We are aware of the issue, and we will do it gracefully until the next release.

**Comment by phax** [comment]
Still open for CII and EDIFACT
