### ISSUE TITLE
Duplicate ID Attributes in EN16931-UBL-codes.sch

### ISSUE THREAD

**Issue by schuetze-alexander-metzner** [ConnectingEurope/eInvoicing-EN16931#69]
[EN16931-UBL-codes.sch](https://github.com/CenPC434/validation/blob/master/ubl/schematron/codelist/EN16931-UBL-codes.sch) contains duplicate ID-Attributes for every `assert`-Tag. This causes XML validation errors when parsing the XML content.

Example from https://github.com/CenPC434/validation/blob/master/ubl/schematron/codelist/EN16931-UBL-codes.sch#L11-L13. I abbreviated the test-expression to make the example more readable.

```xml
<assert
      test="..." id="BR-CL-01" flag="fatal" id="BR-CL-01">...</assert>
```

The duplicated IDs have been introduced with this commit: https://github.com/CenPC434/validation/commit/89a76392ee7be5fbca788b37f634c14a9cc257a5#diff-f5779c4e09ad80ec44e402cbc030de19

**Comment by phax** [comment]
Thanks for pointing that out :)

**Comment by schuetze-alexander-metzner** [comment]
Thanks for the quick response and fix.

**Comment by phax** [comment]
Very good timing from your side :) And it was introduced just a couple of hours before you reported it. So it was a fix for a different fix :) Stay tuned. Release 1.1.0 will be out soon.
