### ISSUE TITLE
UBL rule: BR-CO-25 not firing when PayableAmount is negative

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#7]
BR-CO-25 is not firing when Payable amount is negative

**Comment by oriol** [comment]
The rule says "In case the Amount due for payment (BT-115) is positive, either the Payment due date (BT-9) or the Payment terms (BT-20) shall be present." Should it fire when the payable amount is negative?

**Comment by SiwMeckelborg** [comment]
Sorry, text should be it fires when amount is negative, but is not expected to.

**Comment by oriol** [comment]
((. > 0) and (exists(//cbc:DueDate) or exists(//cac:PaymentTerms/cbc:Note))) or (. <= 0)
