### ISSUE TITLE
Date format YYYY-MM-DD

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#75]
EN 16931-1 requires that date format does not include a specification for the time of the day. 

A check for the correct date format shall be included into CEN schematron.

example for CEN ubl schematron:

```
 <rule context="cbc:IssueDate | cbc:DueDate | cbc:TaxPointDate | cbc:StartDate | cbc:EndDate | cbc:ActualDeliveryDate">
      <assert id="xxx"
              test="string-length(text()) = 10 and (string(.) castable as xs:date)"
              flag="fatal">A date MUST be formatted YYYY-MM-DD.</assert>
    </rule>

```

**Comment by MartinForsberg-Ecru** [comment]
In UBL, the XSD takes care of the data type validation for dates. In CII however, this type of schematron validation is necessary as the syntax binding is done towards the string-alternative of the date-type.

like this: 
		<ram:IssueDateTime>
			<udt:DateTimeString format="102">20180208</udt:DateTimeString>
		</ram:IssueDateTime>

**Comment by MartinForsberg-Ecru** [comment]
one more clarification; When creating the UBL2.0 version the committee decided to split the elements of DateTime-type into seperate elements (like IsssueDate and IssueTime), one with data type Date and one with Time.

**Comment by sarafacchinetti** [comment]
But this value for example passes the ubl xsd 
`<cbc:DueDate>2017-10-30-08:00</cbc:DueDate>`

even though the norm requires YYYY-MM-DD

**Comment by kosek** [comment]
Part "-08:00" is time zone offset, not specification of time. Time zone can be very important if you want to compare date, see e.g. https://www.w3.org/TR/timezone/

**Comment by sarafacchinetti** [comment]
ok, perhaps an explanation could be added in 16931-3-2 about date format in ubl syntax (with or without time zone)

**Comment by phax** [comment]
Okay Sara. We will try to put an explanation at a reasonable place.
