### ISSUE TITLE
Wrong XPATH in BR-CO-26

### ISSUE THREAD

**Issue by rkottmann** [ConnectingEurope/eInvoicing-EN16931#77]
For BT-31: instead of `exists(cac:Party/cac:PartyTaxScheme/cbc:CompanyID)` it should be  `exists(cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:ID)`. The first is not even legal UBL Syntax.

Made pull request #76 

But not for this:

You might also consider to match the order of xpath expressions with the description.

**Comment by oriol** [comment]
BT-31 mapping is correct as it is.
