### ISSUE TITLE
BR-CL-01 clarification

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#78]
This rule checks a list of values (UNTDID 1001) for BT-3
How these values have been selected?
Why in UBL is fatal and in CII is warning?

e.g. Value 202 "Document/message addressed, for instance, by a general contractor to the owner, in order that a direct payment be made to a subcontractor." Is this referring to an invoice?

In addition there are values which are clearly referring to a credit note. There is no distinction in ubl schematron between values referring to an “InvoiceTypeCode” and the ones referring to a “CreditnoteTypeCode”.
Maybe it could be added.

**Comment by phax** [comment]
CEN/TC 434 must decide on the basic rules; the syntaxes have to adopt them;
Link to codelist https://service.unece.org/trade/untdid/d16b/tred/tred1001.htm
Basically a subset of the codelist relevant for EN 16931 is needed

**Comment by oriol** [comment]
The Annex A codelists 20190109 does not distinguish between codes referring to invoices and codes referring to credit notes. Should the artefacts perform this distinction, this Annex should distinguish between them.

As per the severity of the rules, any code list type business rule is considered fatal.

**Comment by sarafacchinettiIC** [comment]
ok, I don't have the lastest version of Annex A codelists but apparently in december version there was the distinction. If it changed no problem.
![image](https://user-images.githubusercontent.com/45999456/52329458-19505e80-29f3-11e9-9119-ddd50a98bf03.png)

Concerning the severity of the rule it looks like is "warning" in CII
![image](https://user-images.githubusercontent.com/45999456/52329619-924fb600-29f3-11e9-84a6-8e16bb37943d.png)

**Comment by oriol** [comment]
Section 6.5.8 Code.Type of the EN says

> The semantic model specifies the code list to be used for each coded business term. Codes shall be entered exactly as shown in the selected code list of the applicable syntax. 

I understand from this statement that the business rules applying to code lists shall raise **fatal** errors and not **warnings**

**Comment by sarafacchinettiIC** [comment]
This code in a UBL credit note is considered as correct by CEN ubl schematron even though value 380 refers to an invoice

`  <cbc:CreditNoteTypeCode>380</cbc:CreditNoteTypeCode>`

the same for the opposite case in a UBL invoice (code 381 meaning credit note)

`<cbc:InvoiceTypeCode>381</cbc:InvoiceTypeCode>`

Do you think an additional rule on CEN UBL schematron will be added to avoid this situation?

**Comment by phax** [comment]
Well, some solutions interpret Negative CreditNotes as invoices...

**Comment by MartinForsberg-Ecru** [comment]
I think it is a problem if you would use code 380 for a credit note. One argument is that such a combination wouldn't be possible to express in CII.
PEPPOL has a rule which captures this. It could be a candidate to move to EN-level.

**Comment by sarafacchinettiIC** [comment]
I agree, in my opinion this rule shall be inserted into CEN ubl schematron
