### ISSUE TITLE
Clarification on the mapping of a percentage to a multiplier

### ISSUE THREAD

**Issue by oriol** [ConnectingEurope/eInvoicing-EN16931#79]
When a percentage is mapped to a multiplier, the content needs to be divided by 100. 

We need to clarify that in the next version of the syntax mapping.

**Comment by phax** [comment]
The goal is to have a `MultiplierFactorNumeric` element with a value range of 0 to 1 meaning 0% to 100%

**Comment by oriol** [comment]
The way is currently stated in the Norm:

> The percentage that may be used, in conjunction with...

suggests that the percentage has to be defined with a number from 0 to 100. Should this be 0 to 1 meaning %, it must be explained in the syntax binding document.

**Comment by sarafacchinettiIC** [comment]
Yes sure, in TS 16931-3-2 it shall be explained that the MultiplierFactorNumeric is within 0 and 1 and there is a data type mismatch  (SYN 3) . For such reason a "transformation logic" is required (multiplied by 100/divided by 100)

**Comment by oriol** [comment]
Current and usual use of the UBL MultiplierFactorNumeric is between 0 and 100, therefore the validation rules will assume the Percentage will be between 0 and 100. 

As agreed in the WG3 for TC434, if you need to express 23.56%, you will add <MultiplierFactorNumeric>23.56</MultiplierFactorNumeric> instead of 0.2356.

**Comment by phax** [comment]
But that contradicts the name of the element. I suggest we ask the OASIS UBL TC if there is an intended (correct) interpretation of this element. If needed, I could contact Ken....

**Comment by oriol** [comment]
Well,  UBL semantics in this case were a little bit forced, as the EN syntax binding is using a Multiplier to represent a Percentage. The semantics of the EN are the ones we should take into account in this case.

**Comment by phax** [comment]
A conversion factor of 100 (12 vs. 0.12) is not a "semantics" of the EN - it's a constant multiplier and as such more a syntax topic. Outside of the EN, the field is used in UBL with the different "syntax". To my understanding this can easily be solved with a corrigendum.

**Comment by oriol** [comment]
Then it is up to the TC to decide issuing a corrigenda if needed...

**Comment by sarafacchinettiIC** [comment]
In official Oasis ubl docs the multiplier is used as number between 0 and 1 (https://docs.oasis-open.org/ubl/prd1-UBL-2.1/mod/summary/reports/UBL-Invoice-2.1.html)

**Comment by sarafacchinettiIC** [comment]
other examples using the multiplier as number between 0 and 1

- https://development.everbinding.nl/knowledge-base/simplerinvoicing-xml-invoice-full/ 
- http://www.oioubl.info/Classes/en/AllowanceCharge.html
- http://www.datypic.com/sc/ubl21/e-cbc_MultiplierFactorNumeric.html
- https://github.com/Tradeshift/tradeshift-ubl-examples/blob/master/src/main/resources/org/oasis-open/ubl/examples/UBL-Invoice-2.1-Example.xml
- https://vefa.difi.no/ehf/g3/billing-3.0/norway/files/ehf-2-faktura-1.xml
- [FAQ16_Allowances_and_ Charges.pdf](https://github.com/CenPC434/validation/files/3121404/FAQ16_Allowances_and_.Charges.pdf)

**Comment by phax** [comment]
* The EN defines BT-94 as to have the semantic type "Percentage"
* The semantic data type "Percentage" has a value range from 0 to 100 (see chapter 6.5.5 EN)
* The TS maps BT-94 to "cbc:MultiplierFactorNumeric" which is according to UBL a "NumericType" -> this is the source of the discrepancy

The problem is, that UBL 2.1 (e.g. the `AllowanceChargeType`) has no element of type "Percentage" that fits, so `MultiplierFactorNumeric` was the best they could come up with, resulting now in this problem.

Imho I don't see a "Semantic issue" when using the value range from 0 to 1 as indicated by UBL, because the "division by 100" is a "transformation" and not a "semantic mapping".
==> So I personally prefer to go for 0..1 and note the necessary division to stick to the syntax (UBL) rules

**Comment by sarafacchinettiIC** [comment]
> Yes sure, in TS 16931-3-2 it shall be explained that the MultiplierFactorNumeric is within 0 and 1 and there is a data type mismatch (SYN 3) . For such reason a "transformation logic" is required (multiplied by 100/divided by 100)

I agree, it is a data type mismatch
