### ISSUE TITLE
xpath error in EN16931-UBL-model, $rate

### ISSUE THREAD

**Issue by PeterOlausson65** [ConnectingEurope/eInvoicing-EN16931#80]
I am using the Schematron files from OpenPEPPOL (https://github.com/OpenPEPPOL/peppol-bis-invoice-3/tree/master/rules/sch) and one of the files CEN-EN16931-UBL.sch gives an xpath error. From what I understand, the CEN-EN16931-UBL.sch is derived from this project.

The error comes from the validation of tax rate, where I believe there is a missing cast to xs:decimal.

> Error on line 3676
>   XPTY0004: Required item type of value of variable $rate is
>   element({urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Percent,
>   xs:anyType); supplied value has item type xs:double
>   at xsl:apply-templates (#2742)
>      processing /Invoice/cac:TaxTotal[1]/cac:TaxSubtotal[1]/cac:TaxCategory[1]
>   at xsl:apply-templates (#2626)
>      processing /Invoice/cac:TaxTotal[1]/cac:TaxSubtotal[1]
>   at xsl:apply-templates (#1807)
>      processing /Invoice/cac:TaxTotal[1]
>   in built-in template rule
>   at xsl:apply-templates (#200)
>      processing /

I got rid of the error by adding the following cast at all places where $rate and cbc:Percent is used.
<assert test="every $rate in xs:decimal(round(cbc:Percent))
was  
<assert test="every $rate in round(cbc:Percent)

**Comment by phax** [comment]
This effects the following rules: `BR-S-08`, `BR-IG-08` and `BR-IP-08`
