### ISSUE TITLE
Possible error in UBL validation

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#81]
When testing the example provided in the UBL syntax binding the example fires error 

"[UBL-CR-114]-A UBL invoice should not include the AdditionalDocumentReference DocumentType."

The syntax binding for BT-18 however qualifies the additional document reference for invoiced object "with cbc:DocumentTypeCode=130". Page 11.

Issue is in line 47

[EN16931 UBL full.txt](https://github.com/CenPC434/validation/files/2511673/EN16931.UBL.full.txt)

**Comment by SiwMeckelborg** [comment]
I think this change should be reversed, as the rule UBL-CR-114 is correct, the rule says:
``` xml
        <assert test="not(cac:AdditionalDocumentReference/cbc:DocumentType)"
         flag="warning"  id="UBL-CR-114">
         [UBL-CR-114]-A UBL invoice should not include the AdditionalDocumentReference 
         DocumentType</assert>
```

The element `cbc:DocumentType` is not used in the syntax mapping, but the element `cbc:DocumentTypeCode` is used to indicate invoice object identifiers (BT-128)

**Comment by oriol** [comment]
I see that both DocumentType and DocumentTypeCode are used. Therefore I suggest removing the rules from the Syntax ruleset.

**Comment by MartinForsberg-Ecru** [comment]
Which BT is mapped to DocumentType? Isn't DocumentDescription used for textual description of the type? It seems to me the rule is correct as it is.

**Comment by oriol** [comment]
DocumentType:
BT-18, BT-123

DocumentTypeCode
BT-128

**Comment by MartinForsberg-Ecru** [comment]
BT-123 is mapped to DocumentDescription.
 ![bild](https://user-images.githubusercontent.com/31277932/52570375-8b6ddc80-2e13-11e9-9345-0d4548d8fe26.png)

BT-18 to DocumentTypeCode
![bild](https://user-images.githubusercontent.com/31277932/52570427-ac363200-2e13-11e9-91ed-294f9f2d0178.png)

**Comment by oriol** [comment]
Right, it was corrected. Will then reverse the rule as it was.
