### ISSUE TITLE
BR-CO-11, BR-CO-12 doubt on doc allowance/charge

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#85]
The rules about totals doc charges and allowances fire correctly if the BT-107 != BT-108

In case BT-107=BT-108 and are NOT present the rules do not fire because the overall invoice amounts are ok but, probably, the rules should fire anyhow because BT-107 and BT-108 are missing.

Could you please have a check on it. An example is attached where BT-107 and BT-108 are commented.

![image](https://user-images.githubusercontent.com/32299198/48130274-66a22000-e28c-11e8-9f00-921d264a82ad.png)

[Test_EeISI_13_docallowancecharge.zip](https://github.com/CenPC434/validation/files/2557269/Test_EeISI_13_docallowancecharge.zip)

**Comment by oriol** [comment]
Corrected adding condition on the allowaces and charges detail. When there are allowances and charges, the total must be specified.
