### ISSUE TITLE
Technical char error in CEN SCH-file

### ISSUE THREAD

**Issue by petersone** [ConnectingEurope/eInvoicing-EN16931#86]
Just downloaded the CEN SCH-file from http://docs.peppol.eu/poacc/billing/3.0/files/CEN-EN16931-UBL.sch
Trying to convert the SCH-file to a XSLT file using Saxon and ANT, I got this error:
[java] I/O error reported by XML parser processing
[java] file:/D:/Projekter/mySupplyProjects/_scripts/target/CEN-EN16931-UBL.step1.xsl: Invalid
[java] byte 3 of 3-byte UTF-8 sequence.
[java] Transformation failed: Run-time errors were reported

Reason for this, are first time found in line 169, errorID=BR-AE-01: ...“Reverse charge”...
The char used as quotation mark are not ASCII 22 (as normal), but some other chars - see attached screenshot from HEX-editor.
Problem occurs multiple times in the file.

Please fix!

/Peter

[CEN-EN16931-UBL.zip](https://github.com/CenPC434/validation/files/2671489/CEN-EN16931-UBL.zip)
![quotationmark](https://user-images.githubusercontent.com/12168546/49863372-73241600-fe00-11e8-854e-cf5d2c191d51.png)

**Comment by petersone** [comment]
Error forwarded to this site/TC434 by PEPPOL: https://openpeppol.atlassian.net/browse/POACC-154

**Comment by phax** [comment]
So to summarize: the copy of the EN 16931 scripts provided in the PEPPOL BIS rules is not an exact copy.
This does not effect the versions on this site. Right?

**Comment by petersone** [comment]
Asking me? Because I don't know... I just downloaded file from http://docs.peppol.eu/poacc/billing/3.0/files/CEN-EN16931-UBL.sch

**Comment by phax** [comment]
Sorry for the stupid question.
I see, that in the references file http://docs.peppol.eu/poacc/billing/3.0/files/CEN-EN16931-UBL.sch the XML signature (`<?xml...?>`) is missing. That means that no encoding is defined meaning that this could mess up the parser.
Comparable files in this repository (as e.g. https://github.com/CenPC434/validation/blob/master/ubl/schematron/EN16931-UBL-model.sch) all have the correct signature, so I assume this is indeed a bug in the PEPPOL rules.

**Comment by MartinForsberg-Ecru** [comment]
Likely reason. I don't get this problem so my parsers seems to treat this as proper utf-8, also without the encoding attribute

**Comment by petersone** [comment]
I cannot reproduce the problem on a direct command line (nice!) - but shouldn't the quotes still be "the right" once?

**Comment by MartinForsberg-Ecru** [comment]
The text is copy-pasted directly from the EN16931-1 and I suppose the editor's word processing software automitically used left double qoute and right double qoute. These followed into the schematron and this works well if the parser assumes the text is UTF-8. So the fix should be to add the XML declaration with the encoding attribute.

**Comment by petersone** [comment]
All other quotes are ACSII (HEX 22) quotes, so wouldn't it be "natual" to use same style all over?

Line 169 from the file:
id="BR-AE-01">[BR-AE-01]-An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is **“**Reverse charge**”** shall contain in the VATBReakdown (BG-23) exactly one VAT category code (BT-118) equal with **"**VAT reverse charge**"**.</assert>

**Comment by phax** [comment]
You are so right :) - just did it

**Comment by oriol** [comment]
Can this issue be closed @phax ?
