### ISSUE TITLE
General VAT rule issues - TaxScheme/cbc:ID not taken into account

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#89]
All rules referring to VAT CategoryCode, Rate, Amount and so on (both in linelevel, allowance and charge and in breakdown) assumes that the tax scheme is VAT without checking. This is causing incorrect invoices to go under the unnoticed in validation. 

Here is an example which would go unnoticed

`
<cac:Item>
            <cbc:Name>Stuff</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>O</cbc:ID>
                <cac:TaxScheme>
                    <cbc:ID>GST</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
`

So for example this rule:
`<assert test="exists(cac:TaxCategory/cbc:ID)" flag="fatal" id="BR-47">[BR-47]-Each VATBreakdown (BG-23) shall be defined through a VAT category code (BT-118).</assert>`

should be implemented like this:
`<assert test="exists(cac:TaxCategory[cac:TaxScheme/cbc:ID='VAT']/cbc:ID)" flag="fatal" id="BR-47">[BR-47]-Each VATBreakdown (BG-23) shall be defined through a VAT category code (BT-118).</assert>`

This also goes for VAT Identifier for Buyer, Seller and TaxRepresentative

**Comment by oriol** [comment]
According to the semantic model, the only tax in the core is VAT. An invoice with GST would be necessarily an extension of the EN, so these rules can be broken.

**Comment by MartinForsberg-Ecru** [comment]
Hi, true, but there is no rule that checks that the scheme is VAT. So any code is currently valid.


________________________________
Från: Oriol Bausa <notifications@github.com>
Skickat: fredag, januari 4, 2019 8:23 fm
Till: CenPC434/validation
Kopia: Martin Forsberg; Author
Ämne: Re: [CenPC434/validation] General VAT rule issues - TaxScheme/cbc:ID not taken into account (#89)


According to the semantic model, the only tax in the core is VAT. An invoice with GST would be necessarily an extension of the EN, so these rules can be broken.

**Comment by oriol** [comment]
Rules affected:
BR-32, BR-37, BR-47, BR-48, BR-CO-04,BR-CO-17,BR-CO-26, BR-S-02,BR-S-03, BR-S-04, BR-Z-01,BR-Z-02,BR-Z-03,BR-Z-04,BR-E-01, BR-E-02,BR-E-03,BR-E-04, BR-AE-01,BR-AE-02,BR-AE-03,BR-AE-04, BR-IC-01, BR-IC-02, BR-IC-03, BR-IC-04, BR-IC-11, BR-IC-12, BR-G-01,BR-G-02,BR-G-03, BR-G-04, BR-O-01, BR-O-02, BR-O-03, BR-O-04, BR-O-11, BR-O-12, BR-O-13, BR-O-14, BR-IG-01, BR-IG-02, BR-IG-03, BR-IG-04, BR-IP-01, BR-IP-02, BR-IP-03, BR-IP-04 and VAT* like contexts.

**Comment by phax** [comment]
Does that check also effect CII???

**Comment by SiwMeckelborg** [comment]
Looking at the CII artefacts, it seems so, yes

**Comment by oriol** [comment]
corrected certain rules where the Seller can have both the VAT identifier or another tax identifier. In those cases we are not checking for the cac:TaxScheme/cbc:ID
