### ISSUE TITLE
UBL rules: BR-S-08 fires when not expected

### ISSUE THREAD

**Issue by SiwMeckelborg** [ConnectingEurope/eInvoicing-EN16931#9]
For rule BR-S-08, if there is a line with VAT rate = 25.0, the rule fires when TaxCategory says 25. 

The rule should not fire just because the number of decimals is not equal, as the value 25.0 is the same as 25 and 25.00

Please see unit test BR-S-08-1, test no 2, which is not expected to fire, but it does.

**Comment by oriol** [comment]
Resolveed rounding Percent
