### ISSUE TITLE
Delete file en16931-xml-validator-0.1.0-jar-with-dependencies.jar that doesn't work

### ISSUE THREAD

**Issue by alexis-via** [ConnectingEurope/eInvoicing-EN16931#90]
I suggest to delete the file "en16931-xml-validator-0.1.0-jar-with-dependencies.jar" which is located in the subdirectory "cii/validator" (and also "edifact/validator"). This file doesn't work and it took me a lot of time before I figured out that I should use https://github.com/CenPC434/java-tools and build the file with maven to generate "en16931-xml-validator-2.0.2-SNAPSHOT-jar-with-dependencies.jar" which works well.

I think it's better to have no JAR file at all than to have a JAR file that doesn't work.
If you delete that file, you should also delete the .sh and .bat scripts that use it, located in the same directory.

**Comment by phax** [comment]
Okidoki

**Comment by phax** [comment]
Validators are kicked - thanks. Instead a list of external services was added.
