### ISSUE TITLE
BT-90 UBL schematron

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#92]
BT-90 can be represented in UBL with same UBL components as BT-29 or BT-60 with "SEPA" as schemeID. If both are present (BT-90 for seller and BT-90 for payee) an error should fire. Probably a rule is missing. Please have a check on it

**Comment by phax** [comment]
UBL-SR-41 was added

**Comment by SiwMeckelborg** [comment]
It seems maybe that the wrong commit has been linked to this issue. When looking at the issue and doing some testing on the rules, it seems that the rule added for this is UBL-SR-41, not 42 as the commit states. However, I am not sure we need rule 41, as there already exist the rule UBL-BR-29, with a fatal error if to occurrences of SEPA identifier is used.

**Comment by sarafacchinettiIC** [comment]
Indeed, please see
https://github.com/CenPC434/validation/issues/104#issuecomment-479046993 

the UBL-BR-29 has been changed after the UBL-SR-41

but there is still issue https://github.com/CenPC434/validation/issues/126 which is pending. I don't know if TC434 discussed it.

**Comment by oriol** [comment]
Remove duplicate rule UBL-SR-41 already covered by UBL-SR-29.

Issue #126 to be resolved by TC 434.
