### ISSUE TITLE
Missing rule for presence of schemeID in Supporting documents (UBL)

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#95]
the schemeID in the Invoiced Object Reference (the schemeID="AOE" in the example below)

```xml
<cac:AdditionalDocumentReference>
  <cbc:ID schemeID="AOE">12345</cbc:ID> 
  <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:AdditionalDocumentReference>
```

Is only allowed to be used when DocumentTypeCode=130. But there is no validation rule to ensure that. 

This example is valid, but shouldn't be according to the semantic model:
```xml
<cac:AdditionalDocumentReference>
  <cbc:ID schemeID="AOE">12345</cbc:ID>
</cac:AdditionalDocumentReference>
```

**Comment by MartinForsberg-Ecru** [comment]
InvoicedObject
![bild](https://user-images.githubusercontent.com/31277932/52489090-ad702080-2bc1-11e9-9678-09be13a6a459.png)

and Supporting Document

![bild](https://user-images.githubusercontent.com/31277932/52489121-b7921f00-2bc1-11e9-9d2f-db8af39d2697.png)

**Comment by oriol** [comment]
Suggest new rule  [UBL-SR-43]-An invoiced object reference shall have a document type code with value 130 and an scheme identifier

**Comment by MartinForsberg-Ecru** [comment]
Shouldn't it be
Scheme identifier shall only be used for Invoiced object (document type code with value 130)
?

**Comment by oriol** [comment]
Agree. Rule changed accordingly.
