### ISSUE TITLE
Missing rule to AddtionalDocumentRef../DocumentTypeCode with other value than 130

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [ConnectingEurope/eInvoicing-EN16931#96]
The DocumentTypeCode in AdditionalDocumentReference can only be used for InvoicedObject and in that case only have value 130. 

There is not validation rule which would pick up this case:
```xml
<cac:AdditionalDocumentReference>
  <cbc:ID schemeID="SZ">12345</cbc:ID>
  <cbc:DocumentTypeCode>131</cbc:DocumentTypeCode> <!-- Value 131 not allowed -->
</cac:AdditionalDocumentReference>
```

**Comment by oriol** [comment]
This is now solved with rule UBL-SR-43 from #95
