### ISSUE TITLE
Violation of cardinality triggers no error signal [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#97]
AccountingSupplierParty/Party/PartyTaxScheme has cardinality 0..2 
Why is no error signal fired in the case below?

	<cac:AccountingSupplierParty>
		<cac:Party>
			<cbc:EndpointID schemeID="0007">5566778899</cbc:EndpointID>
			<cac:PostalAddress>
				<cac:Country>
					<cbc:IdentificationCode>AF</cbc:IdentificationCode>
				</cac:Country>
			</cac:PostalAddress>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AF1234567890</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>123456</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>TAX</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>11112222</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>3rd_OCCURRENCE</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyLegalEntity>
				<cbc:RegistrationName>TESTNAME</cbc:RegistrationName>
			</cac:PartyLegalEntity>
		</cac:Party>
	</cac:AccountingSupplierParty>

Request: Introduce validation rule with severity “fatal”

**Comment by oriol** [comment]
Will add rule UBL-SR-42 Party tax scheme shall occur maximum twice in accounting supplier party
