### ISSUE TITLE
Confusions around supplier’s VAT number - issue 1(2) [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#98]
Suppliers may register themselves for VAT in the home country as well as in some other EU member state(s). But in a specific invoice instance the seller may refer to only one VAT number.  

	<cac:AccountingSupplierParty>
		<cac:Party>
			<cbc:EndpointID schemeID="0007">5566778899</cbc:EndpointID>
			<cac:PostalAddress>
				<cac:Country>
					<cbc:IdentificationCode>AF</cbc:IdentificationCode>
				</cac:Country>
			</cac:PostalAddress>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AF1234567890</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AL123456</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyLegalEntity>
				<cbc:RegistrationName>TESTNAME</cbc:RegistrationName>
			</cac:PartyLegalEntity>
		</cac:Party>
	</cac:AccountingSupplierParty>

The above excerpt would generate 
 “Warning	[UBL-SR-12]-Seller VAT identifier shall occur maximum once”

The potential of a trading party operating with two VAT numbers in parallel in the same transaction is a serious tax issue. 

Request: Raise the severity code to “fatal”.

**Comment by oriol** [comment]
The cardinality in the norm for BT-31 is 0..1, therefore I assume rule UBL-SR-12 can be raised to "fatal".
