### ISSUE TITLE
Confusions around supplier’s VAT number - issue 2(2) [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#99]
Suppliers may register themselves for VAT in the home country as well as in some other EU member state(s). But in a specific invoice instance the seller may refer to only one VAT number. 
At the moment it is possible to register two (or more) VAT numbers by using mixed upper and lower case characters, as in the excerpt below. In a test made this error was not spotted by manual inspection, and the software designer was not aware of any issue.

	<cac:AccountingSupplierParty>
		<cac:Party>
			<cbc:EndpointID schemeID="0007">5566778899</cbc:EndpointID>
			<cac:PostalAddress>
				<cac:Country>
					<cbc:IdentificationCode>AF</cbc:IdentificationCode>
				</cac:Country>
			</cac:PostalAddress>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AF1234567890</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyTaxScheme>
				<cbc:CompanyID>AL123456</cbc:CompanyID>
				<cac:TaxScheme>
					<cbc:ID>vat</cbc:ID>
				</cac:TaxScheme>
			</cac:PartyTaxScheme>
			<cac:PartyLegalEntity>
				<cbc:RegistrationName>TESTNAME</cbc:RegistrationName>
			</cac:PartyLegalEntity>
		</cac:Party>
	</cac:AccountingSupplierParty>   

The potential of a trading party operating with two VAT numbers in parallel in the same transaction is a serious tax issue. 

Request: 
Make the validation of TaxScheme/ID case insensitive for AccountingSupplierParty and, if supplier then has more than one VAT number, generate a fatal error signal.

**Comment by oriol** [comment]
added upper-case control in rule UBL-SR-12
